### ISSUE TITLE
Adding competition

### ISSUE THREAD

**Issue by Jes-Lop** [JaseZiv/worldfootballR#12]
Perhaps this should go elsewhere but, would it be possible to add the Spanish Second Division to the competitions? The data is here: [https://fbref.com/en/comps/17/history/Segunda-Division-Seasons](url). It would be very interesting to have this available. 

Sorry if this is not the correct place.

Thanks for this great job.

**Comment by JaseZiv** [comment]
This is definitely the right place to raise this.

Currently the data from fbref is for tier 1 domestic competitions,  but can be expanded on in the future for sure.

**Comment by Jes-Lop** [comment]
Thanks JaseViz, will wait. Data for Spain SmartBank League (or Second Division) is [here](https://fbref.com/en/comps/17/Segunda-Division-Stats). Stats for teams are [here](https://fbref.com/en/squads/2aa12281/Mallorca-Stats) and for matches [here](https://fbref.com/en/comps/17/schedule/Segunda-Division-Scores-and-Fixtures). Excuse my ignorance, I don't know if this is enough data to be included in the package or how difficult it can be. Thank you very much for paying attention to me.  :)

**Comment by JaseZiv** [comment]
> Thanks JaseViz, will wait. Data for Spain SmartBank League (or Second Division) is [here](https://fbref.com/en/comps/17/Segunda-Division-Stats). Stats for teams are [here](https://fbref.com/en/squads/2aa12281/Mallorca-Stats) and for matches [here](https://fbref.com/en/comps/17/schedule/Segunda-Division-Scores-and-Fixtures). Excuse my ignorance, I don't know if this is enough data to be included in the package or how difficult it can be. Thank you very much for paying attention to me. :)

**Comment by JaseZiv** [comment]
This has now been handled in version 0.2.4
