### ISSUE TITLE
Unavailable to retrieve data from several functions from fotmob

### ISSUE THREAD

**Issue by Pablo-Alvarez-Baeza** [JaseZiv/worldfootballR#122]
I'm getting this issue with several functions from fotmob:

library(worldfootballR)
library(dplyr)
library(tidyr)

epl_team_xg_2021 <- fotmob_get_season_stats(
  country = "ENG",
  league_name = "Premier League",
  season_name = "2020/2021",
  stat_name = "Expected goals",
  team_or_player = "team"
)

Error: Expected to find `table` or `tables` element but did not.
Error: Document is empty
In addition: Warning message:
Unknown or uninitialised column: `page_url`.

**Comment by JaseZiv** [comment]
It appears as though fotmob have changed some URL endpoints. 

[This issue](https://github.com/JaseZiv/worldfootballR/issues/121) is also linked to this.

Given fotmob tend to change these semi-regularly, then back again, maybe we hold off pushing any changes for a few days... Thoughts @tonyelhabr?

**Comment by tonyelhabr** [comment]
> Thanks for submitting.
> 
> It appears as though fotmob have changed some URL endpoints.
> 
> [This issue](https://github.com/JaseZiv/worldfootballR/issues/121) is also linked to this.
> 
> Given fotmob tend to change these semi-regularly, then back again, maybe we hold off pushing any changes for a few days... Thoughts @tonyelhabr?

I think the best solution is to take the fotmob functions out of this package. I'll make a package just for fotmob that should not be expected to be as robust as `{worldfootballR}`
