### ISSUE TITLE
Unable to install package for R

### ISSUE THREAD

**Issue by mroker242** [JaseZiv/worldfootballR#125]
Hello, I am unable to install R on both Windows and Mac machines and getting the error:

Warning in install.packages :
  package ‘worldfootballR’ is not available for this version of R

Which version needs to be installed?

**Comment by JaseZiv** [comment]
You need to have at least R version 4.0 installed.

**Comment by SeriyBg** [comment]
It seems like the package is not available via CRAN. Installing with `devtools` should work though

**Comment by JaseZiv** [comment]
> It seems like the package is not available via CRAN. Installing with `devtools` should work though

Ah yes that's my bad - I need to update the docs to inform users that the library is no longer on CRAN.

Thanks for the reminder!
