### ISSUE TITLE
Error in open.connection(x, "rb") :    SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by prowe8** [JaseZiv/worldfootballR#144]
Hi all, trying to create pizza plots using ggshakeR and getting this error message consistently: Error in open.connection(x, "rb") : 
  SSL certificate problem: certificate has expired 

Full code + error message is here: > single_player <- fb_player_scouting_report("https://fbref.com/en/players/f586779e/Tammy-Abraham", pos_versus = "primary")
Error in open.connection(x, "rb") : 
  SSL certificate problem: certificate has expired
> 
> pizza <- plot_pizza(data = single_player, type = "single", template = "forward", 
+                     color_possession = "#41ab5d", color_attack = "#fec44f", color_defense = "#de2d26", 
+                     season = "Last 365 Days", theme = "dark")
Error in filter(., scouting_period == season) : 
  object 'single_player' not found
> 
> pizza
Error: object 'pizza' not found

Really not sure how to solve it as my OS is up to date as well - any help would be appreciated! Don't think I'm blocked from Fbref as can still use the website etc

**Comment by tonyelhabr** [comment]
Possibly relevant: https://github.com/JaseZiv/worldfootballR/issues/138#issuecomment-1162835376

**Comment by JaseZiv** [comment]
Can confirlm the SSL certificate problem is rectified upgrading the OS. Will close this issue for now.
