### ISSUE TITLE
fbref match urls from last season ending 2022 don't load

### ISSUE THREAD

**Issue by gilberke** [JaseZiv/worldfootballR#154]
Eng2022MatchUrls<-get_match_urls(country = "ENG", gender = "M", season_end_year = c(2022))
(The same if I want "FRA" data.)

Then I get an empty list of values.

**Comment by JaseZiv** [comment]
Sorry about this - the process that goes and updates the season URLs for new seasons hadn't yet happened. This should be all good to go now.

**Comment by gilberke** [comment]
Thank you! (And also for the excellent package!)

Op wo 3 aug. 2022 00:17 schreef Jason Zivkovic ***@***.***>:
