### ISSUE TITLE
fb_big5_advanced_season_stats with season end year = 2022 returning 2023 values

### ISSUE THREAD

**Issue by yonilavi8** [JaseZiv/worldfootballR#158]
Hello,

I attempted to retrieve defensive stats from all players in the big5 leagues from last season, but when using 2022 as an input the function returns this season's (year end 2023) players and their stats. Although, it seams to correctly work when using 2021 (and earlier years).

Here is what I used:
big5_player_def <- fb_big5_advanced_season_stats(season_end_year= 2022, stat_type= "defense", team_or_player= "player")

Appreciate any help, thanks :)

**Comment by JaseZiv** [comment]
This has been addressed with in the most current dev version (`v 0.5.10`). Install via GitHub.

Also important to remember, for past data (well and will update during the weeks of the season also), there are load functions which will get you what you need https://jaseziv.github.io/worldfootballR/reference/load_fb_big5_advanced_season_stats.html

**Comment by yonilavi8** [comment]
Thanks for the help! Much appreciated 👍
