### ISSUE TITLE
get_match_summary not loading data

### ISSUE THREAD

**Issue by adammurphyucc** [JaseZiv/worldfootballR#162]
Hi,

match <- get_match_urls(country = "ENG", gender = "M", season_end_year = 2023, tier = "1st")
df <- get_match_summary(match_url = match)

I return df which is empty
![image](https://user-images.githubusercontent.com/95476274/184101646-8b315f9a-df6c-4e94-bac3-7a4aca6974d9.png)

**Comment by JaseZiv** [comment]
Working on a fix for this.

The same issue is causing this issue https://github.com/JaseZiv/worldfootballR/issues/157.

The next update will address this.

Thanks

**Comment by JaseZiv** [comment]
This issue has been somewhat resolved now with the most recent dev version release (`0.5.11.1000`).

The `get_` functions have now been replaced with `fb_`.

Additionally, the following functions now no longer return league/season metadata, including columns `League`, `Gender`, `Country`, `Season`:

`fb_match_summary()`
`fb_advanced_match_stats()`
`fb_match_report()`

Please let me know if there's any other problems
