### ISSUE TITLE
Closing unused connection

### ISSUE THREAD

**Issue by pacoca43** [JaseZiv/worldfootballR#163]
Hi, 
I am trying to download player data for some La Liga teams and R is returning the following errors:

Warning messages:                                                                                                                     
1: In for (j in pseq) if (length(lij <- all.levs[[j]])) value[[j]] <- factor(as.vector(value[[j]]),  :
  closing unused connection 4 (https://www.transfermarkt.com/luka-modric/profil/spieler/27992)
2: In for (name in names(public_methods)) lockBinding(name, public_bind_env) :
  closing unused connection 3 (https://www.transfermarkt.com/toni-kroos/profil/spieler/31909)

Warning messages:                                                                                                    
1: In .Internal(lapply(X, FUN)) :
  closing unused connection 3 (https://www.transfermarkt.com/robin-le-normand/profil/spieler/351809)

This is hapening not in all teams. The process does not stop, only the error player does not appear in the csv that is generated.

The code for all teams is: 
_real_madrid_pl_bios<- tm_team_player_urls("https://www.transfermarkt.com/real-madrid/startseite/verein/418/saison_id/2022")
real_madrid_pl_bios
RM_bios<- tm_player_bio(player_urls = real_madrid_pl_bios)
write.csv(x=RM_bios, file = "BIOS EQUIPOS 22-23/1ESP/RM_bios.csv", row.names = FALSE)_

Thanks

**Comment by JaseZiv** [comment]
The warnings are fine here.

I've tried running the code you provided and I get no errors at all.

What version of the package are you using?

**Comment by pacoca43** [comment]
I'm using 0.5.7 version

**Comment by JaseZiv** [comment]
Try updating to the latest version using
`devtools::install_github("JaseZiv/worldfootballR") `.

let me know how you go

**Comment by pacoca43** [comment]
All packages updated. R updated. But I still get the same error randomly. I send you code with error and without error executed consecutively. I think it must be my computer's fault. I don't know. Thanks for your attention.


_> getafe_pl_bios<- tm_team_player_urls("https://www.transfermarkt.com/fc-getafe/startseite/verein/3709/saison_id/2022")
> GET_bios<- tm_player_bio(player_urls = getafe_pl_bios)
Warning messages:                                                                                                              
1: In for (i in seq_along(transliterations)) { :
  closing unused connection 4 (https://www.transfermarkt.com/david-soria/profil/spieler/226012)
2: In for (i in seq_along(transliterations)) { :
  closing unused connection 3 (https://www.transfermarkt.com/fc-getafe/startseite/verein/3709/saison_id/2022)
3: In for (name in names(public_methods)) lockBinding(name, public_bind_env) :
  closing unused connection 3 (https://www.transfermarkt.com/damian-suarez/profil/spieler/76746)
> write.csv(x=GET_bios, file = "BIOS EQUIPOS 22-23/1ESP/GET_bios.csv", row.names = FALSE)

> getafe_pl_bios<- tm_team_player_urls("https://www.transfermarkt.com/fc-getafe/startseite/verein/3709/saison_id/2022")
> GET_bios<- tm_player_bio(player_urls = getafe_pl_bios)
> write.csv(x=GET_bios, file = "BIOS EQUIPOS 22-23/1ESP/GET_bios.csv", row.names = FALSE)__

**Comment by pacoca43** [comment]
I have just discovered that the problem is caused by my workplace wifi network. I don't know if it's due to micro-cuts in the connection or what else, but that was the problem.

Thanks
