### ISSUE TITLE
Discrepancy Between tm_expiring_contracts by country_name and league_url

### ISSUE THREAD

**Issue by mintcityanalytics** [JaseZiv/worldfootballR#167]
Pulling expiring contracts across multiple leagues and tried scraping from transfermarkt by the country name and league url resulted in dataframes with some players missing from scraping by one of the methods.

I tested across multiple leagues and the omissions are not consistent by scraping by country or league url. For example league_url pulls more names than country_name for the Premier League, but less for La Liga.

**Comment by JaseZiv** [comment]
Hi,

Thanks for raising.

Can you please provide some code that you’re using to see these results?

**Comment by mintcityanalytics** [comment]
Sure. 

I'll start with the Premier League. If you scrape transfermarkt by leagueu_rl:

epl_expiring <- tm_expiring_contracts(country_name = "",
  contract_end_year = 2023,
  league_url = "https://www.transfermarkt.us/premier-league/startseite/wettbewerb/GB1")

You get a dataframe of 113 observations of 14 variables. If you then try scraping by country_name:

eng_1_expiring <- tm_expiring_contracts(country_name = "England",
   contract_end_year = 2023)

Dataframe produced has 138 observations of 14 variables. I went through a few of the names missing and I wasn't able to pick up on any particular patterns. So, in this case, scraping by country_name provides a list with more names. When we try with Spain's La Liga:

laliga_expiring <- tm_expiring_contracts(country_name = "",
  contract_end_year = 2023,
  league_url = "https://www.transfermarkt.us/laliga/startseite/wettbewerb/ES1")

The league_url process produces 122x14 dataframe. Whereas if we pull by country_name in this situation:

spa_1_expiring <- tm_expiring_contracts(country_name = "Spain",
  contract_end_year = 2023)

Dataframe is 72x14, so league_url produces more names in this example. 

I first noticed the discrepancy when I received an "Error: HTTP error 403." scraping Belgium's Jupiler Pro League by league_url, switching to country_name, and exporting the csv and it had a different number than my first scrape of the JPL by league_url.

**Comment by JaseZiv** [comment]
This is interesting and I wonder whether it's a problem on the site's side... I have just tried to recreate the error and I get identical results using either method:

```library(worldfootballR)

# EPL ---------------------------------------------------------------------
epl_expiring <- tm_expiring_contracts(country_name = "",
                                      contract_end_year = 2023,
                                      league_url = "https://www.transfermarkt.us/premier-league/startseite/wettbewerb/GB1")
# dimensions using the league_url:
dim(epl_expiring)
# [1] 137  14

eng_1_expiring <- tm_expiring_contracts(country_name = "England",
                                          contract_end_year = 2023)
# are identical to using country_name:
dim(eng_1_expiring)
# [1] 137  14



# La Liga -----------------------------------------------------------------
laliga_expiring <- tm_expiring_contracts(country_name = "",
                                         contract_end_year = 2023,
                                         league_url = "https://www.transfermarkt.us/laliga/startseite/wettbewerb/ES1")
# dimansions using the league_url:
dim(laliga_expiring)
# [1] 121  14

spa_1_expiring <- tm_expiring_contracts(country_name = "Spain",
                                          contract_end_year = 2023)
# are identical to using country_name:
dim(spa_1_expiring)
# [1] 121  14
```

The output of my `sessionInfo()` is below:

```
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.5.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] worldfootballR_0.5.12.3000

loaded via a namespace (and not attached):
 [1] pillar_1.7.0      compiler_4.2.0   
 [3] prettyunits_1.1.1 remotes_2.4.2    
 [5] tools_4.2.0       pkgbuild_1.3.1   
 [7] jsonlite_1.8.0    lubridate_1.8.0  
 [9] lifecycle_1.0.1   tibble_3.1.7     
[11] pkgconfig_2.0.3   rlang_1.0.2      
[13] cli_3.3.0         DBI_1.1.2        
[15] rstudioapi_0.13   curl_4.3.2       
[17] xml2_1.3.3        withr_2.5.0      
[19] dplyr_1.0.9       httr_1.4.3       
[21] stringr_1.4.0     janitor_2.1.0    
[23] hms_1.1.1         generics_0.1.2   
[25] vctrs_0.4.1       rprojroot_2.0.3  
[27] tidyselect_1.1.2  glue_1.6.2       
[29] snakecase_0.11.0  R6_2.5.1         
[31] processx_3.5.3    fansi_1.0.3      
[33] selectr_0.4-2     tidyr_1.2.0      
[35] tzdb_0.3.0        readr_2.1.2      
[37] callr_3.7.0       purrr_0.3.4      
[39] magrittr_2.0.3    ps_1.7.0         
[41] ellipsis_0.3.2    rvest_1.0.2      
[43] assertthat_0.2.1  utf8_1.2.2       
[45] stringi_1.7.6     crayon_1.5.1
```

Can you try again to see if it's resolved itself for you too?

**Comment by JaseZiv** [comment]
Will mark this as closed unless you're still having this issue @mintcityanalytics? If so, comment here and I'll reopen.
