### ISSUE TITLE
Running into Cloud fare issues when scrapping FBREF

### ISSUE THREAD

**Issue by SangeethsivanSivakumar** [JaseZiv/worldfootballR#169]
Hi, it seems the website doesn't want you to scrape data so it blocks requests by the code and blocks it. I tried increasing the sleep time as well. How do you get around it?

**Comment by JaseZiv** [comment]
Hi there,

Can you please provide the code that has caused you some issues? I am working on something that I hope will fix this in the near future.

**Comment by SangeethsivanSivakumar** [comment]
Hi my colleague and I just realised it's scrapping again. We think reducing the frequency you send requests to fbref to once about every 12-24 hours works. I'll close the issue for now, but would be interested in your solution if it's better. Thank you
