### ISSUE TITLE
get_season_team_stats advanced stats error

### ISSUE THREAD

**Issue by szfh** [JaseZiv/worldfootballR#17]
`get_season_team_stats("ENG","M","2020","standard")`

> Error in gsub("\\+", "_plus_", names(stat_df)) : 
>   object 'stat_df' not found

Changes in fbref back end cause `get_season_team_stats` to fail for all stat types except `league_table` and `league_table_home_away`.

**Comment by JaseZiv** [comment]
Thanks for creating the issue and providing an MRE. Will hopefully have this fixed in the next day or so. Sorry for the inconvenience

**Comment by szfh** [comment]
No problem! I won't mess with your code but it looks like the tables have been renamed on the site.

![image](https://user-images.githubusercontent.com/52595717/110946066-5a37a180-8336-11eb-968d-551db3f1dd3c.png)

**Comment by szfh** [comment]
Thanks so much, just needs a git merge I think 😃
