### ISSUE TITLE
Error in `.fotmob_get_stat_and_season_options()`:

### ISSUE THREAD

**Issue by OKcomputer626** [JaseZiv/worldfootballR#170]
Hello,
I am using the latest version of the worldfootballr package 0.5.12.1000, and I'm encountering an error using the fotmob_get_season_stats() function when extracting Liga MX of unable to retrieve information.

**Code:** 
`liga_mx <- fotmob_get_season_stats(
  country = "MEX",
  league_name = "Liga MX",
  season = "2022/2023",
  stat_name = "Expected goals",
  team_or_player = "team"
)`

**Output:**
Error in `.fotmob_get_stat_and_season_options()`:
! Season ids not stored in expected format at https://www.fotmob.com/leagues/230/stats/liga-mx/teams.
Run `rlang::last_error()` to see where the error occurred.

Any help would be appreciated.
Thanks,
Andres

**Comment by tonyelhabr** [comment]
Please re-install the package with `remotes::install_github("JaseZiv/worldfootballR")` and try

```r
liga_mx <- fotmob_get_season_stats(
  country = "MEX",
  league_name = "Liga MX",
  season = "2022/2023-Apertura",
  stat_name = "Expected goals",
  team_or_player = "team"
)
```

**Comment by OKcomputer626** [comment]
It worked! Thanks a lot! @tonyelhabr
