### ISSUE TITLE
fb_match_urls function not found?

### ISSUE THREAD

**Issue by raahulbi103** [JaseZiv/worldfootballR#175]
Kept getting the following error message when trying to scrape FBRef match URLs, would appreciate any help with this!

```
> epl_2021_urls <- fb_match_urls(country = "ENG", gender = "M", season_end_year = 2021, tier="1st")
Error in fb_match_urls(country = "ENG", gender = "M", season_end_year = 2021,  : 
  could not find function "fb_match_urls"
```

**Comment by JaseZiv** [comment]
What version of the package are you using? If current, try restarting your R session, loading libraries and then trying again

**Comment by raahulbi103** [comment]
Whoops just saw this, I'll try that again

**Comment by raahulbi103** [comment]
Okay the package was fine, but I updated R and tried again and it worked, thanks a lot!
