### ISSUE TITLE
fb_player_match_logs Error

### ISSUE THREAD

**Issue by azzlam97** [JaseZiv/worldfootballR#176]
Some players return an error when using the fb_player_match_logs function (e.g. Martinelli, Demarai Gray)

Error is as follows:
```
fb_player_match_logs('https://fbref.com/en/players/48a5a5d6/Martinelli', 2023, 'summary')
Error in `dplyr::mutate()`:
! Problem while computing `Squad = sub("^.*?([A-Z])", "\\1", .data$Squad)`.
Caused by error in `.data$Squad`:
! Column `Squad` not found in `.data`.
---
Backtrace:
  1. worldfootballR::fb_player_match_logs(...)
 14. rlang:::abort_data_pronoun(x, call = `y)
```

**Comment by JaseZiv** [comment]
Hi,

Can you please provide the output of `sessionInfo()`?

I have run the example you have provided and found no issues. Make sure you're version of `worldfootballR` is current (`0.6.0`).

**Comment by azzlam97** [comment]
Interesting, all seems to be working fine now?
Thanks for your response nonetheless
