### ISSUE TITLE
Discrepancy in how ```fb_season_team_stats()``` reports Austrian Bundesliga

### ISSUE THREAD

**Issue by Paulj1989** [JaseZiv/worldfootballR#177]
There is a discrepancy in the way that FB Ref reports the Austrian Bundesliga league table in the seasons since the league was restructured for the 2018/19 season.

<details>
<summary>Context: Austrian Bundesliga Restructure</summary>
<br>
Prior to the 2018/19 season, the Austrian Bundesliga consisted of ten teams that play each other four times each season, totaling 36 games, with the team that finishes in first place winning the league, and the team that finishes in 10th playing a promotion/relegation playoff against the winner of the Austrian 2. Liga to decide the 10th team in the next BuLi season.

For the 2018/19 season up to the present day, the BuLi was restructured to expand the number of teams from 10 to 12. The league season is now split into a regular season with each team playing each other twice, totaling 22 games, before the league is split into two, with the top six teams from the regular season entering a championship round and the bottom six teams entering a relegation round, where each team will play each other twice more, totaling another 10 games. 

Each club begins with half the points earned in the regular season, rounded down. The final table in the championship round determines the order of the top 6 finishers in Bundesliga, and the vice versa in the relegation round.
<br>
</details>

For the [2018/19](https://fbref.com/en/comps/56/2018-2019/2018-2019-Austrian-Bundesliga-Stats) and [2019/20](https://fbref.com/en/comps/56/2019-2020/2019-2020-Austrian-Bundesliga-Stats) seasons, FB Ref reports a league table that is the combined totals of both the regular season and the championship/relegation rounds (with the details of the regular season and the playoff rounds reported on the same page below). From the [2020/21](https://fbref.com/en/comps/56/2020-2021/2020-2021-Austrian-Bundesliga-Stats) season onward, they have reported the regular season as the league table (with playoff rounds reported below). 

This leads to a discrepancy in the league tables that ```fb_season_team_stats()``` pulls for each of these seasons, making comparison between seasons rather difficult!

**Reprex:**

``` r
library(worldfootballR)
library(dplyr)

austrian_buli <-
  fb_season_team_stats(
    country = "AUT",
    gender = "M",
    season_end_year = c(2018:2022),
    tier = "1st",
    stat_type = "league_table",
    time_pause = 5
  )

austrian_buli %>%
  filter(Season_End_Year == 2022) %>%
  select(Squad, MP, Pts) %>%
  arrange(desc(Pts)) %>%
  head()
#>                   Squad MP Pts
#> 1           RB Salzburg 22  55
#> 2            Sturm Graz 22  37
#> 3        Wolfsberger AC 22  37
#> 4          Austria Wien 22  33
#> 5            Rapid Wien 22  31
#> 6 SK Austria Klagenfurt 22  30

austrian_buli %>%
  filter(Season_End_Year == 2020) %>%
  select(Squad, MP, Pts) %>%
  arrange(desc(Pts)) %>%
  head()
#>            Squad MP Pts
#> 1    RB Salzburg 32  74
#> 2           LASK 32  64
#> 3     Rapid Wien 32  58
#> 4 Wolfsberger AC 32  54
#> 5   Austria Wien 32  47
#> 6       Hartberg 32  42

austrian_buli %>%
  filter(Season_End_Year == 2018) %>%
  select(Squad, MP, Pts) %>%
  arrange(desc(Pts)) %>%
  head()
#>         Squad MP Pts
#> 1 RB Salzburg 36  83
#> 2  Sturm Graz 36  70
#> 3  Rapid Wien 36  62
#> 4        LASK 36  57
#> 5      Admira 36  51
#> 6 Mattersburg 36  46
```

<sup>Created on 2022-09-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This obviously isn't an issue of worldfootballR's creation, but I thought it worth mentioning so that you are aware of it!

I'm not sure if it's worth considering amending the way the function pulls the data for these seasons, either using the regular season or a combined aggregate table, for consistency? I'm also not sure which would be the preferred approach, if you were to do so.

**Comment by Paulj1989** [comment]
Also worth noting that there doesn't appear to be any discrepancy in how they report player stats in these seasons, as they use the combined totals for each season, so this issue should only be limited to the league tables.

**Comment by Paulj1989** [comment]
Quick update: I got in touch with Adam at FB Ref and let him know about the issue, and I think he's going to get that fixed. Will close this once the fix is in place at FB Ref and no longer filtering through to worldfootballR,

**Comment by JaseZiv** [comment]
Awesome, thanks for following this up with the source @Paulj1989!

**Comment by Paulj1989** [comment]
All looks like it is resolved on RB Ref's side now, so doesn't require a solution on the worldfootballR end. Problem solved!
