### ISSUE TITLE
Error: object 'fb_player_goal_logs' not found

### ISSUE THREAD

**Issue by Jes-Lop** [JaseZiv/worldfootballR#181]
New fb_player_goal_logs() or fb_team_goal_logs does not appear after install new development version. 

using  R version 4.2.0 (2022-04-22) gives: Error: object 'fb_player_goal_logs' not found or 'fb_team_goal_logs' not found

**Comment by JaseZiv** [comment]
I think I know what has gone wrong here so I’ll get it sorted shortly.

Thanks for raising

**Comment by JaseZiv** [comment]
@Jes-Lop This should now be fixed. Reinstall and make sure you have `v0.6.0.2000` installed.

Thanks again

**Comment by Jes-Lop** [comment]
Works fine now. Thanks!
