### ISSUE TITLE
fb_team_goal_logs not work in several leagues

### ISSUE THREAD

**Issue by Jes-Lop** [JaseZiv/worldfootballR#182]
Sorry to boring you again. fb_team_goal_logs don't work in Spanish leagues (neither LaLiga nor second division). Work fine in english premier (and maybe others I haven't tested it). I get this error:
fb_team_goal_logs(team_urls = "https://fbref.com/en/squads/7848bd64/Getafe-Stats", for_or_against = "both")
Error in xml_nodeset(NextMethod()) : 
  Expecting an external pointer: [type=NULL]

Regards.

**Comment by JaseZiv** [comment]
This should now be all fixed with the most recent dev version (`0.6.0.3000`).

Will close for now but feel free to post here if needed.

Thanks

**Comment by Jes-Lop** [comment]
Thanks for work. In spanish second division fix not work: 
fb_team_goal_logs(team_urls = "https://fbref.com/en/squads/a0435291/Granada-Stats", for_or_against = "for") gives this error (same with both or against parameters):
Error in `.data$Body.Part`:
! Column `Body.Part` not found in `.data`.
Run `rlang::last_error()` to see where the error occurred.

Regards
