### ISSUE TITLE
duplicate urls

### ISSUE THREAD

**Issue by szfh** [JaseZiv/worldfootballR#19]
```
league_urls <- fb_league_urls("ENG","M",2020) %>% print
  
match_urls <- get_match_urls("ENG","M",2020) %>% print

```
These functions get each expected URL twice instead of once, maybe because of duplicated lines data in the raw-data folder.

**Comment by JaseZiv** [comment]
Fixed with commit https://github.com/JaseZiv/worldfootballR/commit/7306e1e58bdc764266469a0b3669162e5c3e694a
