### ISSUE TITLE
Issue with `fotmob_get_season_stats( )`

### ISSUE THREAD

**Issue by mcavs** [JaseZiv/worldfootballR#201]
I received the following error to call the season stats by using `fotmob_get_season_stats( )`. How can I solve this? 

```
> epl_team_xg_2021 <- fotmob_get_season_stats(
+   country = "ENG",
+   league_name = "Premier League",
+   season_name = "2020/2021",
+   stat_name = "Expected goals",
+   team_or_player = "team"
+ )

Error: lexical error: invalid char in json text.
                                       NA
                     (right here) ------^
```

**Comment by JaseZiv** [comment]
Tagging @tonyelhabr here as this does appear to be an issue.

I have recreated it locally using version `0.6.1.4000` and can confirm the error is occurring.

**Comment by tonyelhabr** [comment]
i'll take a look at it tomorrow

**Comment by tonyelhabr** [comment]
> i'll take a look at it tomorrow

Ah, this is quite involved. Seems that they have changed the way that they store the data.

**Comment by mcavs** [comment]
@tonyelhabr is this error solved? Because I still received the same error...

**Comment by tonyelhabr** [comment]
Ah yes it's broken again. fotmob changes their website very frequently. as you can see, there was [no failed test](https://github.com/JaseZiv/worldfootballR/actions/runs/3361462748/jobs/5571888819) for line 188 in `test-fotmob.R` when the PR merged (that test has essentially the same code as yours)

**Comment by tonyelhabr** [comment]
@mcavs can you try it again? i just tried the function call and it worked.

for some context: i was debugging the issue last night and saw some big changes that Fotmob implemented on the backend (different format for build id, parameters in the query component of the URL), but I came back to it this morning and no longer saw the same changes

**Comment by mcavs** [comment]
@tonyelhabr it works now. Thanks for your interest!

**Comment by cjones46** [comment]
@tonyelhabr I'm still receiving the lexical error running the exact same command. I've updated the worldfootballR package and restarted R. Any suggestions?

**Comment by cjones46** [comment]
@tonyelhabr Updated the package, verified that my version is > 1.8.1, but still getting the same error unfortunately.

```
> packageVersion("jsonlite")
[1] ‘1.8.3’
> epl_team_xg_2021 <- fotmob_get_season_stats(country = "ENG", league_name = "Premier League", season_name = "2020/2021", stat_name = "Expected goals",team_or_player = "team")
Error: lexical error: invalid char in json text.
                                       NA
                     (right here) ------^
```

**Comment by tonyelhabr** [comment]
@cjones46 hmm ok i'll look into this more this evening

**Comment by tonyelhabr** [comment]
@cjones46 I realized that I forgot to ask what version of the `{worldfootballR}` package you have. Do you have at least `0.6.1.5000`?

**Comment by cjones46** [comment]
@tonyelhabr 

Doesn't appear that I do; I ran update.packages() on it at the beginning of this conversation and thought that meant I had the latest version, but it doesn't seem to have given me a version 0.6.1.5000. How do I obtain that version?

```
> packageVersion("worldfootballR")
[1] ‘0.6.1’
> update.packages("worldfootballR")
> packageVersion("worldfootballR")
[1] ‘0.6.1’
```

**Comment by tonyelhabr** [comment]
Try `remotes::install_github("JaseZiv/worldfootballR")`

**Comment by cjones46** [comment]
@tonyelhabr 

That worked! Thank you so so much for your help and for the great work you guys do to keep up this wonderful package!

**Comment by tonyelhabr** [comment]
> @tonyelhabr
> 
> That worked! Thank you so so much for your help and for the great work you guys do to keep up this wonderful package!

awesome!
