### ISSUE TITLE
fotmob_get_season_stats PROBLEM

### ISSUE THREAD

**Issue by mcefis** [JaseZiv/worldfootballR#205]
Good morning, 

unfortunately I have this output problem with the fotmob function **fotmob_get_season_stats** :
**Error: lexical error: invalid char in json text.
                                       NA
                     (right here) ------^**

Can you help me to fix this error?

Many thanks

Mattia

**Comment by tonyelhabr** [comment]
What version of the package do you have? If you don't have the latest version, please try on the latest version.

FWIW I can't seem to replicate [this issue](https://github.com/JaseZiv/worldfootballR/issues/201#issuecomment-1300507230) on version 0.6.1.5000.

**Comment by mcefis** [comment]
Now I have installed the version 0.6.1.6000 and it's ok, thanks!
