### ISSUE TITLE
Error in fotmob_get_league_matches()

### ISSUE THREAD

**Issue by smhrt08** [JaseZiv/worldfootballR#206]
I have been encountering the errors when trying to use this function. Even when using the examples in the help it throws the same error. Wasn't sure if maybe the structure of the response had changed or something, or if it was user error on my part. 

```
fotmob_get_league_matches(league_id = 47)
Error in clean_names.default(.) : 
  No `clean_names()` method exists for the class list
Consider janitor::make_clean_names() for other cases of manipulating vectors of names.
```

**Comment by tonyelhabr** [comment]
What version of the package do you have? Can you ensure that you have at least `0.6.1.5000`?

**Comment by smhrt08** [comment]
I had 0.6.1, but the version update you sent worked. Thank you!
