### ISSUE TITLE
Error in fb_advanced_match_status in brazillian league

### ISSUE THREAD

**Issue by LuccaStochiero** [JaseZiv/worldfootballR#208]
One especific game in 2022 Brazilian League is not available in 'fb_advanced_match_status' with stat_type = 'misc'.
I used the league and match url to get all matches

--- fb_advanced_match_stats(urls, stat_type = 'misc', team_or_player = 'team')         
---Stats data not available for https://fbref.com/en/matches/8e04e63c/Santos-Internacional-June-8-2022-Serie-A )

**Comment by JaseZiv** [comment]
Hi,

Can you please confirm what version you are using? The current dev version is `0.6.1.6000`. I have tested locally using this version and it returns the data needed.

Make sure you're up to date with this.
