### ISSUE TITLE
`tm_expiring_contracts()` not able to run for multiple countries

### ISSUE THREAD

**Issue by JaseZiv** [JaseZiv/worldfootballR#212]
`tm_expiring_contracts()` only works for one country at a time. So this throws errors:

```
big_five <- c("Spain", "France", "England", "Italy", "Germany")

big5 <- tm_expiring_contracts(country_name = big_five , contract_end_year = "2023")
```

While this doesn't:

```
fra <- worldfootballR::tm_expiring_contracts(country_name = "France" , contract_end_year = "2023")
```

**Comment by nepito** [comment]
Hi @JaseZiv,

I could take on this issue if you are interested.
I'll refactor the function first since it is longer than 100 lines.
What do you think?

**Comment by JaseZiv** [comment]
> Hi @JaseZiv,
> 
> 
> 
> I could take on this issue if you are interested.
> 
> I'll refactor the function first since it is longer than 100 lines.
> 
> What do you think?

Sure thing. 

Reach out if you need to discuss.

Thanks heaps
