### ISSUE TITLE
fb_player_scouting_report() only returning standard stats

### ISSUE THREAD

**Issue by rougvie** [JaseZiv/worldfootballR#213]
The dataframes produced by fb_player_scouting_report() currently only return statistics from the standard statistics of fbref, as opposed to the full scouting report that was previously produced. 

For what it may be worth:
I have run into this problem both for players in top 5 leagues and in the newly added leagues for advanced statistics.
I'm on version 0.6.1.6000, and installed via githubinstall

I'd assume this is caused by the recent change in data providers, but figured it put it out here.

Thank you in advance!

**Comment by JaseZiv** [comment]
We can only scrape whatever is provided. If what you see on screen is being returned by the functions, then that is all we can get.

I suspect this is definitely due to the change in FBRef's data providers.

Can you confirm that the function is working as expected so I can close this issue?
