### ISSUE TITLE
Issue in fotmob_get_league_matches()

### ISSUE THREAD

**Issue by evirgen1** [JaseZiv/worldfootballR#214]
I had a problem when I used worldfootballr package. 

This code is working:

`df1 <- fotmob_get_league_tables(country = "TUR", league_name = "Super Lig")`

But, when I try this: 

`new <- fotmob_get_league_matches(country = "TUR", league_name = "Super Lig")`

I am getting this error:  "Error is: Error in clean_names.default(.) : 
  No `clean_names()` method exists for the class list
Consider janitor::make_clean_names() for other cases of manipulating vectors of names."

I do not understand the reason of this error. Thank you!

**Comment by JaseZiv** [comment]
I have tested this locally on the current dev version (`0.6.1.6000`). I think the problem you're having is you're not using the most current version. Always make sure you're using the latest version - we're constantly updating the library to account for html changes on the sites we're scraping.

We can only push changes to CRAN monthly at most, so always check what dev version we're on.

You can install it using:

```
devtools::install_github("JaseZiv/worldfootballR")
```

**Comment by evirgen1** [comment]
Thank you! It worked!
