### ISSUE TITLE
tm_team_transfer_balances not working

### ISSUE THREAD

**Issue by drasbaek** [JaseZiv/worldfootballR#215]
I am not able to use the tm_team_transfer_balances function, despite it having worked in the past. It is regardless of the country and year i specfify.

For instance, when I write:

`tm_team_transfer_balances(country = "England", start_year = 2022)`

I get:

`Error in data.frame(country = country_name, league = league_name, season = season,  : 
  arguments imply differing number of rows: 0, 1`

I assume this is a bug relating to how the information is being scraped from transfermarkt?

**Comment by JaseZiv** [comment]
I have tested this locally on the current dev version (`0.6.1.6000`). I think the problem you're having is you're not using the most current version. Always make sure you're using the latest version - we're constantly updating the library to account for html changes on the sites we're scraping.

We can only push changes to CRAN monthly at most, so always check what dev version we're on.

You can install it using:

```
devtools::install_github("JaseZiv/worldfootballR")
```

Please install the update and let me know here. If it works with the latest version, I will close this issue.

**Comment by drasbaek** [comment]
I was on version 0.6.1 only - updating to the dev version fixed the issue. Thanks!
