### ISSUE TITLE
fb_player_season_stats() for national team stats

### ISSUE THREAD

**Issue by vennanalysis** [JaseZiv/worldfootballR#222]
Trying to pull national team stats using this function - see code example below. Both lines return the club level stats. Let me know if there is another function/method for this

`fb_player_season_stats("https://fbref.com/en/players/abb3bb95/Luuk-de-Jong", stat_type = 'playing_time')
fb_player_season_stats("https://fbref.com/en/players/abb3bb95/Luuk-de-Jong-National-Team-Stats", stat_type = 'playing_time')`

Thanks

**Comment by JaseZiv** [comment]
Unfortunately this function only gets league based data, and excludes a player's international stats...

I will leave this open as a possible new function/addition to the existing `fb_player_season_stats` function.
