### ISSUE TITLE
fotmob_get_league_matches() returns error

### ISSUE THREAD

**Issue by FelixZhao123** [JaseZiv/worldfootballR#223]
The function fotmob_get_league_matches returns error mesages as below:

`> league_matches <- fotmob_get_league_matches(
+   country =     c("ENG",            "ESP"   ),
+   league_name = c("Premier League", "LaLiga")
+ )
Error in clean_names.default(.) : 
  No `clean_names()` method exists for the class list
Consider janitor::make_clean_names() for other cases of manipulating vectors of names.`

would you please take a look into this? 
Thanks!

**Comment by nikhil18jj** [comment]
Same issue,all the fotmob functions don't work.

**Comment by FelixZhao123** [comment]
Thanks! It worked after updating to latest version.
