### ISSUE TITLE
Error message in fb_match_urls function

### ISSUE THREAD

**Issue by raahulbi103** [JaseZiv/worldfootballR#236]
Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

If you don't already have the lastest version of the package, please try downloading it with `remotes::install_github("JaseZiv/worldfootballR")`, restarting your R session, and then trying your code againl.

When submitting your issue, feel free to delete everything above the line below, since this text is just intended to help you submit an informative issue.

---
Hi, when using the fb_match_urls function, R returns the error 'cannot open the connection". I've tried uninstalling and reinstalling the package, and restarting the R session, which haven't worked. Would love to know if something is wrong on my end or if this is a package issue, thanks!

```r
>library(worldfootballR)
> prem_urls <- fb_match_urls(country = "ENG", gender = "M", season_end_year = 2023, tier="1st")
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  InternetOpenUrl failed: 'An error occurred in the secure channel support'

```

**Comment by jayhaytch** [comment]
Working on my machine, [check this out](https://stackoverflow.com/questions/27466317/error-in-filefile-rt-cannot-open-the-connection) though, seems to be your issue

**Comment by raahulbi103** [comment]
Yeah, looked these up but those solutions are for opening/accessing a .csv file present on the system, which isn't the case here. I've checked out a couple of other places now and it seems like it might be something to do with a secure connection or something
