### ISSUE TITLE
Error in fotmob_get_league_matches

### ISSUE THREAD

**Issue by JNAnalytica** [JaseZiv/worldfootballR#238]
Caused by error in 'map()':

In index: 1.

Caused by error inf():

Argument 1 must have names.

fotmob_get_league matches

Error in map2()":

In index: 1. Caused by error in "map():

In index: 1. Caused by error in 'map():

In index: 1.

Caused by error info:

Argument 1 must have names. Run clang::last_error) to see where the error occurred.

Error occuring when trying to pull matches using function, error listed above

**Comment by JaseZiv** [comment]
Can you please provide the code you used that lead to the error. Additionally, can you also include the output of `sessionInfo()`

**Comment by tonyelhabr** [comment]
Yes, please make sure you're on the latest version of the package, which you can get with `remotes::install_github("JaseZiv/worldfootballR")`. See #237.

**Comment by JNAnalytica** [comment]
leagues <- read.csv("https://raw.githubusercontent.com/JaseZiv/worldfootballR_data/master/raw-data/fotmob-leagues/all_leagues.csv")
comp_id = 48
league_matches <- fotmob_get_league_matches(
  league_id = comp_id) 

Have updated to the latest version and has resolved the issue, had a different version of the package in my library to what was on my drive. Thank you for the help
