### ISSUE TITLE
Understat shot functions all broken

### ISSUE THREAD

**Issue by JaseZiv** [JaseZiv/worldfootballR#239]
All `understat_` shooting functions are no longer returning results. It appears as though the `script` with the `var name` is no longer exposed to `rvest` scraping.

Will investigate a solution.

**Comment by afc04** [comment]
Adding that understat_league_match_results() also seems broken:

```
>   epl_understat <- understat_league_match_results(league = "EPL", season_start_year = 2022)
Error in do.call(data.frame, out_df) : second argument must be a list
```
