### ISSUE TITLE
fb_player_scouting_report function issue

### ISSUE THREAD

**Issue by jonas-richter** [JaseZiv/worldfootballR#242]
Dear JaseZiv,

Thanks for this great package, I've been using it a lot recently. Since a few days I'm facing a problem with the fb_player_scouting_report function, which throws an error message every time I run it with any player (using latest package version). An example is

`fb_player_scouting_report(player_url = "https://fbref.com/en/players/d70ce98e/Lionel-Messi", pos_versus = "primary")`

I think the problem is at this part of the function but don't know how to fix it:
`period <- scout_pg %>% rvest::html_nodes("#all_scout") %>% 
      rvest::html_nodes(".section_heading_text") %>% rvest::html_text() %>% 
      unique() %>% stringr::str_squish()`

Maybe you know a solution? Thank you!

**Comment by JaseZiv** [comment]
Thanks for raising this.

I will look into it and keep this thread updated.

**Comment by JaseZiv** [comment]
I’ve got a fix, and enhancement for this function ready to go. Will push it though in the next few days after a feature request is pushed.

**Comment by jonas-richter** [comment]
Amazing, thanks!

**Comment by coder-GP** [comment]
I am also receiving errors when using this function. For any player, I get " Full scouting report not available for [player]". Furthermore, when I try to add the optional league_comp_name, I get "unused argument (league_comp_name = "Last 365 Days Men's Big 5 Leagues, UCL, UEL")".

**Comment by jonas-richter** [comment]
For me the function works like this (see attachment). 
[function.txt](https://github.com/JaseZiv/worldfootballR/files/10483806/function.txt)

**Comment by JaseZiv** [comment]
> I am also receiving errors when using this function. For any player, I get " Full scouting report not available for [player]". Furthermore, when I try to add the optional league_comp_name, I get "unused argument (league_comp_name = "Last 365 Days Men's Big 5 Leagues, UCL, UEL")".

Can you please confirm what version of `worldfootballR` you're using?

**Comment by coder-GP** [comment]
> > I am also receiving errors when using this function. For any player, I get " Full scouting report not available for [player]". Furthermore, when I try to add the optional league_comp_name, I get "unused argument (league_comp_name = "Last 365 Days Men's Big 5 Leagues, UCL, UEL")".
> 
> Can you please confirm what version of `worldfootballR` you're using?

I believe it is the CRAN version.

**Comment by JaseZiv** [comment]
> > > I am also receiving errors when using this function. For any player, I get " Full scouting report not available for [player]". Furthermore, when I try to add the optional league_comp_name, I get "unused argument (league_comp_name = "Last 365 Days Men's Big 5 Leagues, UCL, UEL")".
> > 
> > 
> > Can you please confirm what version of `worldfootballR` you're using?
> 
> I believe it is the CRAN version.

That's definitely out of date then.

Please install the most recent dev version from GitHub.

Thanks

**Comment by scott2491** [comment]
I'm getting the same full player report not available issue.

I've installed from github like you have suggested.
`install_github("JaseZiv/worldfootballR", force = TRUE)`

I've then ran the messi example.
`messi_last_365 <- fb_player_scouting_report(player_url = "https://fbref.com/en/players/d70ce98e/Lionel-Messi",
                                            pos_versus = "primary")`

With the following output
Error in fb_player_scouting_report(player_url = "https://fbref.com/en/players/d70ce98e/Lionel-Messi",  : 
  Full scouting report not available for Lionel Messi

I must be doing something wrong as you seem to have fixed it. Would you kindly advise please?

**Comment by JaseZiv** [comment]
> messi_last_365 <- fb_player_scouting_report(player_url = "https://fbref.com/en/players/d70ce98e/Lionel-Messi", pos_versus = "primary")

@scott2491, After reinstalling the library, did you restart a new R session? If not, do that and try again. I have just tested the function using `v0.6.1.9000` and returned results successfully.

If you have done the above, can you please also run `sessionInfo()` in RStudio and paste the results here?

Thanks

**Comment by scott2491** [comment]
> > messi_last_365 <- fb_player_scouting_report(player_url = "https://fbref.com/en/players/d70ce98e/Lionel-Messi", pos_versus = "primary")
> 
> @scott2491, After reinstalling the library, did you restart a new R session? If not, do that and try again. I have just tested the function using `v0.6.1.9000` and returned results successfully.
> 
> If you have done the above, can you please also run `sessionInfo()` in RStudio and paste the results here?
> 
> Thanks

Yeah, it seems to be working now. I must of not restarted the session, my bad! Thanks for the quick help though!
