### ISSUE TITLE
FBref Scouting Report

### ISSUE THREAD

**Issue by lucassvarelaa** [JaseZiv/worldfootballR#255]
I was trying to use the scouting report function but it didn't work with any player link. I even tried the example given on the package's website and nothing. Here's the error:
Error in fb_player_scouting_report(player_url = "https://fbref.com/en/players/d70ce98e/Lionel-Messi",  : 
  Full scouting report not available for Lionel Messi

```r
library(worldfootballR)
packageVersion("worldfootballR")

messi_primary <- fb_player_scouting_report(player_url = "https://fbref.com/en/players/d70ce98e/Lionel-Messi", pos_versus = "primary")

sessionInfo()
```

**Comment by andiyudha** [comment]
I still found this issue, do you have any resolving idea?

**Comment by JaseZiv** [comment]
> I still found this issue, do you have any resolving idea?

What version of `worldfootballR` are you using? If it's not `v0.6.2.9400`, then that's probably your problem.

If so, install the latest dev version using:

```
devtools::install_github("JaseZiv/worldfootballR")
```

**Comment by andiyudha** [comment]
> > I still found this issue, do you have any resolving idea?
> 
> What version of `worldfootballR` are you using? If it's not `v0.6.2.9400`, then that's probably your problem.
> 
> If so, install the latest dev version using:
> 
> ```
> devtools::install_github("JaseZiv/worldfootballR")
> ```

I have resolved after updating through the dev version... Thanks
