### ISSUE TITLE
Error Fotmob function: fotmob_get_match_players

### ISSUE THREAD

**Issue by Gyracat** [JaseZiv/worldfootballR#264]
I already update lastest version and i found this 

Error: length(starters) == 2 is not TRUE

**Comment by gitboyzorro5** [comment]
Me too i have a problem with this function.It does not return the expected data.on running it gives the following output.
# A tibble: 0 x 1
# ... with 1 variable: match_id <int>

**Comment by tonyelhabr** [comment]
Yes we're aware. A lot of changes need to be made, see #263. I will have time to fix things on the weekend.

**Comment by tonyelhabr** [comment]
addressed with #266
