### ISSUE TITLE
No marketvalues for players < 1m with `tm_player_marketvalues()`

### ISSUE THREAD

**Issue by drasbaek** [JaseZiv/worldfootballR#265]
HI! When running the `tm_player_marketvalues()` function, I get NAs in the column for `player_market_value_euro` column for all players with a marketvalue below 1 million. 

I assume it has to do with the conversion of the html text elements that are formattet as €XXXk instead of millions?

For example, this code:
```r
library(worldfootballR)
tm_player_market_values("England", 2022)
```

It will give NA for players such as Willy Caballero and Jack Colback even though they have a sub-million marketvalue available.

**Comment by JaseZiv** [comment]
Hi there,

Can you please provide your output of calling `sessionInfo()`?

I have tried to run the code using the most recent version of {worldfootballR} (`0.6.3.0000`) on MacOS and have returned a player value for Willy Caballero of 200k:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/31471783/231633341-1114712e-e8ad-4400-baf3-65d45caf6b16.png">

**Comment by drasbaek** [comment]
Upon closer inspection, it seems to have been an outdated version of stringi that caused the error - updating my dependencies fixed the issue. Issue closed.

**Comment by datakacs22** [comment]
Hi, I have the exact same problem with market values below 1M (and also player age). I am quite new to worldfootballR and R in general. Already updated stringi but didn't solve the problem. I attached a screenshot of the sessioninfo(). Thank you in advance!

![sessioninfo](https://github.com/JaseZiv/worldfootballR/assets/137234769/61cd4c80-6767-4fa3-83bd-297913b8dbe3)

**Comment by ucce87** [comment]
Hi, same issue here: all the players with a value <1M have "NA".
All the packages are up to date.
Thank you!
