### ISSUE TITLE
`tm_player_injury_history` pulls in no data

### ISSUE THREAD

**Issue by bonddr** [JaseZiv/worldfootballR#268]
I have tried to run the following: `tm_player_injury_history("https://www.transfermarkt.com/manchester-city/startseite/verein/281/saison_id/2020")`

I get the following error:
Error: Problem while computing `injured_since = lubridate::ymd(.data[["injured_since"]])`.

**Comment by JaseZiv** [comment]
Hi there,

Thanks for raising.

This particular example you've raised isn't an issue, rather an incorrect use of the function.

You have provided a team URL to the `tm_player_injury_history()` function, where you need to provide a player URL(s).

This works:

```
# for Ederson's Injury history
player_injuries <- worldfootballR::tm_player_injury_history("https://www.transfermarkt.com/ederson/profil/spieler/238223")

# for all Man City 2020-21 players injury histories: 
players <- worldfootballR::tm_team_player_urls("https://www.transfermarkt.com/manchester-city/startseite/verein/281/saison_id/2020")
player_injuries <- worldfootballR::tm_player_injury_history(player_urls = players)
```

I will however keep this open as a bug as I've noticed the `player_name` column is also getting the player number and causing issues with output format:

![image](https://user-images.githubusercontent.com/31471783/231642152-5409f703-1bfe-42e6-beed-d81977b42ddc.png)
