### ISSUE TITLE
Fotmob Functions not working

### ISSUE THREAD

**Issue by mbrownsword** [JaseZiv/worldfootballR#275]
fixtures <- fotmob_get_league_matches(league_id = id, cached = FALSE)
Error in `map()`:
i In index: 1.
Caused by error in `unpack()`:
! Names must be unique.
x These names are duplicated:
  * "localizedName" at locations 5 and 7.
i Use argument `names_repair` to specify repair strategy.
Run `rlang::last_trace()` to see where the error occurred.

This is an example of what happens when i run fotmob_get_league_matches, but the same thing occurs when i run fotmob_get_league_ids

**Comment by dammfoolman** [comment]
I get the following using the function below  

[1] 4140722 
fotmob_get_match_details(4140722) 
Error: incorrect number of dimensions 
# A tibble: 0 × 1 # ℹ 1 variable: match_id <int>
--

**Comment by grrooooot** [comment]
I might be facing same issues with fotmob functions.
<img width="222" alt="image" src="https://github.com/JaseZiv/worldfootballR/assets/45707081/00eb0233-76fe-4a84-a059-adc76ace1c1f">
