### ISSUE TITLE
Error in fotmob_get_match_players()

### ISSUE THREAD

**Issue by cg86x** [JaseZiv/worldfootballR#277]
Getting an error with the below code. Was working as recently as yesterday.
`
fotmob_get_match_players(2999743)

Error: ℹ In index: 1.
Caused by error in `map2()`:
ℹ In index: 3.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `dimnames(X) <- list(dn[[1L]], unlist(collabs[nc > 0], use.names = FALSE))`:
! length of 'dimnames' [2] not equal to array extent
# A tibble: 0 × 1
# ℹ 1 variable: match_id <int>

`

For the record, using Fotmob API directly works fine so it isn't an API issue. I've reinstalled, restarted, and otherwise tried all options to resolve the error.

Using Mac OS, package version 0.6.3.3.

**Comment by tonyelhabr** [comment]
not entirely sure if there is an easy fix. looks like they added an extra layer of nesting

![image](https://github.com/JaseZiv/worldfootballR/assets/15663460/87a678ed-985d-43a0-bc2f-1683eee8bbee)

**Comment by PatrikHed** [comment]
The layer in the players array was always there. But they seem to have added a layer in the Bench part of the response. My own parser for the API is breaking because it tries to access bench[0]. Fix would be to access bench.benchArr[0].

![image](https://github.com/JaseZiv/worldfootballR/assets/54438119/6dbc2b63-2a3f-495f-8d10-e29c1081ad2f)

**Comment by tonyelhabr** [comment]
ok i made some progress tracking down the bug. seems like there's an issue with `as.matrix.data.frame()` when `t()` is called [here](https://github.com/JaseZiv/worldfootballR/blob/0f19861571b42c86155791972d67b79cf1237635/R/fotmob_players.R#L85). working on a fix now

addendum to my last comment: i'm not actually sure the level of nesting changed at all

**Comment by cg86x** [comment]
This is great - thanks for taking a look and getting to the bottom of it!

**Comment by Gyracat** [comment]
Now , I can run this function?
