### ISSUE TITLE
fotmob_get_match_players not bringing through data

### ISSUE THREAD

**Issue by Lano-23** [JaseZiv/worldfootballR#288]
I'm unable to get data back from the "fotmob_get_match_players" function which was previously working.  Has something changed with the fotmob website?

e.g. Match_Player_Stats = fotmob_get_match_players(4074401)

Many thanks

Paul

**Comment by gitboyzorro5** [comment]
Me too am experiencing same problem...is there a major change @JaseZiv and @tonyelhabr?

**Comment by mbrownsword** [comment]
i am also having this issue

**Comment by gitboyzorro5** [comment]
Thanks @tonyelhabr it seems to be working using your instructions.
