### ISSUE TITLE
`get_match_results()` before 2014-15 season

### ISSUE THREAD

**Issue by tonyelhabr** [JaseZiv/worldfootballR#29]
The following returns the `Data not available for the season(s) selected`.

```
res <- worldfootballR::get_match_results(country = "ENG", gender = "M", season_end_year == 2013)
```

I believe the same error also occurs for the other Big 5 leagues for Men's 1st Tier and for seasons before 2014-15 season. I believe the issues is due to empty "Time" columns on the fixtures page

![time](https://user-images.githubusercontent.com/15663460/116910714-9affb880-ac0b-11eb-91ed-fb85421ddfff.PNG)

I think this can be resolved fairly easily with the following change [here](https://github.com/JaseZiv/worldfootballR/blob/7ba3c937ef4454cbcf81b51c3224054497f10f67/R/get_match_results.R#L75)

```
dplyr::filter(is.na(.data$Time) | .data$Time != "Time")
```

I'll leave it up to you to decide if you think this is the right change. If so, let me know if you'd like me to submit a pull request.

**Comment by JaseZiv** [comment]
Thanks for picking this up! I just committed a [quick fix](https://github.com/JaseZiv/worldfootballR/commit/7a9c16ef19ab2bc33e3df53879c25530f2561bfb) so you didn't need to worry about doing it. Thanks again!
