### ISSUE TITLE
[Bug] Get Data in Function fotmob_get_match_players , data in some column it's Duplicate data

### ISSUE THREAD

**Issue by Gyracat** [JaseZiv/worldfootballR#304]
I want to get data in premier league 2022-2023 (GW1-GW38) for summary report data ,i found bug in many column wrong data 

library(worldfootballR)
packageVersion("worldfootballR")

AllmatchGW<-fotmob_get_match_players(c(3900932,#GW1
                                       3900933,
                                       3900934

))

![correct](https://github.com/JaseZiv/worldfootballR/assets/79399115/4cf82d1e-b9f4-4548-aa74-0bced7624598)

(Correct Data,i already get data in GW1 started)

![wrong](https://github.com/JaseZiv/worldfootballR/assets/79399115/4af8868e-903c-4c9a-90d5-de7833dcae9d)

(Wrong Data.Today i already check Match_ID again and run check)

Please investigate this bug.

**Comment by Gyracat** [comment]
Now I received the data. It's okay. I don't know if it's because of the internet or not that the data in the retrieval is wrong.

**Comment by tonyelhabr** [comment]
thank you for clarifying that you were able to get the data
