### ISSUE TITLE
Fbref Fixtures for upcoming season

### ISSUE THREAD

**Issue by cg86x** [JaseZiv/worldfootballR#307]
serieA_2024 <- fb_match_results(country = "ITA", gender = "M", season_end_year = 2024, tier = "1st")

Error in fb_match_results(country = "ITA", gender = "M", season_end_year = 2024,  : 
  Data not available for the season(s) selected

Does something need to be preloaded on your side to grab upcoming fixtures? The upcoming fixtures are available at the fbref url:

https://fbref.com/en/comps/11/2023-2024/schedule/2023-2024-Serie-A-Scores-and-Fixtures

Thanks!

**Comment by francescozonaro** [comment]
Are you still having problems with this? Seems to be working fine with

```
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)
worldfootballR_0.6.3.0013
```

**Comment by cg86x** [comment]
Seems to be working now. Thanks!
