### ISSUE TITLE
Cannot access FBref data from last season

### ISSUE THREAD

**Issue by solsterg98** [JaseZiv/worldfootballR#313]
Hi there @JaseZiv,

I have been using your package for a few months now and it's been great! 

However for some reason today I cleared all the data from my Rstudio environment and went to redownload the data using the following function:

``` {r}
big5_player_shooting <-fb_big5_advanced_season_stats(season_end_year= c(2023), stat_type= "shooting", team_or_player= "player")
```
I am trying to get the data from the 22-23 season but now it seems to give me the data from the new season, and excludes data from Serie A and the Bundesliga as I guess they haven't started yet.

Any help would be greatly appreciated :)

**Comment by JaseZiv** [comment]
Hi there,

Can you confirm that this is now working again as expected?

**Comment by solsterg98** [comment]
Yep it's all working again. 

Thank you!
