### ISSUE TITLE
fotmob functions disapeared

### ISSUE THREAD

**Issue by SRRTD** [JaseZiv/worldfootballR#316]
{{Brief description of the problem}}

when trying to create a match report using old scripts I managed to track an error to the fotmob shot data functions returning empty tibbles. after updating the package to the latest github version i found that all functions prefixed by fotmob are no longer on the package. i'm unsure if this is due to fotmob being removed from the supported websites (there seems to be some indication on this on previous issues, but i'm unsure) or an installation error on my part.

I can't provide a reproducible example, since the error is just that the functions weren't found. thanks in advance :)

**Comment by Gyracat** [comment]
@tonyelhabr

**Comment by tonyelhabr** [comment]
https://github.com/JaseZiv/worldfootballR/pull/311

**Comment by SRRTD** [comment]
oh that's a shame, but it's understandable. 

is there an alternative to find the location on goal of shots? neither fbref nor understat seem to have it

**Comment by tonyelhabr** [comment]
> oh that's a shame, but it's understandable. 
> 
> is there an alternative to find the location on goal of shots? neither fbref nor understat seem to have it
> 

no public source that i know of

**Comment by SRRTD** [comment]
that's a bit of a problem for me then. thank you though, i'll close this.
