### ISSUE TITLE
event_half column for get_match_summary()

### ISSUE THREAD

**Issue by szfh** [JaseZiv/worldfootballR#32]
Events in first half stoppage time can cause unusual results, for example:

```
url <- "https://fbref.com/en/matches/9f0275a4/North-West-Derby-Manchester-United-Liverpool-May-13-2021-Premier-League"

match_goals <-
  url %>%
  get_match_summary() %>%
  filter(event_type=="Goal") %>%
  select(event_time:score_progression)
```
Has a goal scored in the 48th minute of the first half and the 47th minute of the second half, which can cause errors.

![image](https://user-images.githubusercontent.com/52595717/118683831-989b8200-b7f9-11eb-8511-fec3faca0bf5.png)

A simple solution is something like below (but probably won't deal with extra-time matches well).
```
mutate(event_half=ifelse(as.numeric(str_sub(time,1,2)) <= 45,1,2))
```

**Comment by JaseZiv** [comment]
The function now returns a few additional columns. 

**NOTE:** Column names have changed so will break existing code.

The original MRE you sent:
```
url <- "https://fbref.com/en/matches/9f0275a4/North-West-Derby-Manchester-United-Liverpool-May-13-2021-Premier-League"

match_goals <-
  url %>%
  get_match_summary() %>%
  filter(Event_Type=="Goal") %>%
  select(Event_Time:Penalty_Number)
```
![image](https://user-images.githubusercontent.com/31471783/118956337-da1b6100-b9a2-11eb-9191-f5fcc8a40953.png)

But also handles matches with penalty shoot-outs:
```
wc_url <- "https://fbref.com/en/matches/bd1fbaf4/Russia-Croatia-July-7-2018-FIFA-World-Cup"

world_cup_match_goals <-
  wc_url %>%
  get_match_summary() %>%
  filter(Event_Type=="Goal") %>%
  select(Event_Time:Penalty_Number)
```
![image](https://user-images.githubusercontent.com/31471783/118956511-02a35b00-b9a3-11eb-9bd5-5fd57d31ff71.png)
