### ISSUE TITLE
load_match_results() not fetching data from German leagues

### ISSUE THREAD

**Issue by Binisteri** [JaseZiv/worldfootballR#323]
Fetching German leagues doesn't work. Tested different divisions and other countries - they work.

```r
library(worldfootballR)
packageVersion("worldfootballR")

#load_match_results(country = 'GER', gender = 'M', season_end_year = c(2017:2024), tier = '1st')

sessionInfo()
```

**Comment by JaseZiv** [comment]
This should now be fixed. 

I will close this issue for now, but please comment/reopen if you still find errors.

Thanks
