### ISSUE TITLE
add remaining contract duration to transfer history

### ISSUE THREAD

**Issue by DiegoRibas97** [JaseZiv/worldfootballR#34]
Hi Jason, first of all Thank you very much for your package. It's really useful and I have a lot of fun using it and experimenting with all the data. I am currently trying to use machine learning to predict transfer fees. Therefore it would be very useful to include the remaining contract duration of players that are transferred to another club. transfermarkt.com provides this information for most transfers, but you have to look into transfer details for each single transfer. Do you think it would be possibly to extract this information? 
As an example, why it would be interesting to look at contract durations:
https://www.transfermarkt.com/leroy-sane/transfers/spieler/192565/transfer_id/1556750
https://www.transfermarkt.com/leroy-sane/transfers/spieler/192565/transfer_id/2954050

**Comment by JaseZiv** [comment]
Hi there, this could be valuable information, you're right!

I'll investigate how hard it is to get this info.

Follow here for updates.

Jason

**Comment by JaseZiv** [comment]
This will be addressed in the next release coming in the next day or so.

Thanks for the suggestion @DiegoRibas97!
