### ISSUE TITLE
Problem with Installation

### ISSUE THREAD

**Issue by lucassvar** [JaseZiv/worldfootballR#347]
I tried to re-install the package to try to solve a problem in one of my apps. After uninstalling the library I tried to install it and got an error.
The issue appears to be with the repository or the package itself rather than my local setup. The error occurred during the installation process and is related to a file (fb_league_stats.R) within the 'worldfootballR' package.
The error message indicates an issue at line 204 in the 'fb_league_stats.R' file. Specifically, it points to an unexpected input at that line.

**Comment by JaseZiv** [comment]
Can you please include the specific error message you get?
