### ISSUE TITLE
Data Inaccuracies when retrieving historic player value data

### ISSUE THREAD

**Issue by jf632** [JaseZiv/worldfootballR#350]
---

There are many data inaccuracies that are present in the dataframes returned by ```tm_player_market_values```. For example, this is what the row for Azpilicueta is: 

Premier League | Europe | England | 2015 | Chelsea FC | - | César Azpilicueta | Attacking Midfield | 1996-11-09 | NA | Jamaica | Coventry City | 1.75 | right | NA | NA | NA | NA | https://www.transfermarkt.com/cesar-azpilicueta/profil/spieler/57500 | Chelsea FC

Which is inaccurate as he has never played for Coventry and is not Jamaican. 

```r
library(worldfootballR)
packageVersion("worldfootballR")

epl_valuations <- tm_player_market_values(country_name = "England", start_year = 2015)

sessionInfo()
```

**Comment by JaseZiv** [comment]
Can you please provide the output of `sessionInfo()`? Ensure you're using the most recent dev release of `worldfootballR` from GitHub, which is `0.6.4.14`.

I'm not able to reproduce your issue. 

Running the following code:

```
epl_valuations <- worldfootballR::tm_player_market_values(country_name = "England", start_year = 2015)

epl_valuations |> 
  dplyr::filter(player_name == "César Azpilicueta") |> 
  dplyr::glimpse()
```

Yields the following results (which are correct):

```
Rows: 1
Columns: 19
$ comp_name                <chr> "Premier League"
$ region                   <chr> "Europe"
$ country                  <chr> "England"
$ season_start_year        <int> 2015
$ squad                    <chr> "Chelsea FC"
$ player_num               <chr> "28"
$ player_name              <chr> "César Azpilicueta"
$ player_position          <chr> "Right-Back"
$ player_dob               <date> 1989-08-28
$ player_age               <dbl> 26
$ player_nationality       <chr> "Spain"
$ current_club             <chr> "Atlético de Madrid"
$ player_height_mtrs       <chr> "1.78"
$ player_foot              <chr> "right"
$ date_joined              <chr> "2012-08-24"
$ joined_from              <chr> "Olympique Marseille"
$ contract_expiry          <chr> NA
$ player_market_value_euro <dbl> 2e+07
$ player_url               <chr> "https://www.transfermarkt.com/cesar-azpilicueta/profil/…
```

**Comment by jf632** [comment]
Hi,

Thanks for your answer, I was using the CRAN installation, I have switched to the dev release and the information is now accurate.

Thank you
