### ISSUE TITLE
Feature request: Transfermarkt player suspension & absences history

### ISSUE THREAD

**Issue by yonilavi8** [JaseZiv/worldfootballR#352]
Hi there. Would it be possible to request a function which returns the suspension & absences history of players given a player url (similar to querying transfermarkt for player injury history)? For example, I would like to access data from the table shown here: 
<https://www.transfermarkt.co.uk/nicolas-jackson/ausfaelle/spieler/776890>

Something like this maybe?

```
tm_player_suspension_history(player_urls = "https://www.transfermarkt.co.uk/nicolas-jackson/profil/spieler/776890")
```

If this functionality exists already and I may have missed it please lmk. Any help is appreciated :)

**Comment by JaseZiv** [comment]
Thanks for the request.

I will look in to this to see how easy it will be to get. Good suggestion.

Thanks
