### ISSUE TITLE
fb_player_scouting_report() returns only the "Last 365 Days Men's Big 5 Leagues, UCL, UEL" scouting period

### ISSUE THREAD

**Issue by SeriyBg** [JaseZiv/worldfootballR#360]
Tried with Pulisic:
```
data <- fb_player_scouting_report("https://fbref.com/en/players/1bf33a9a/Christian-Pulisic", pos_versus="primary", league_comp_name="Serie A")
```

**Expected:**
The result should include different `scouting_period`

**Actual:**
The result includes only the values for `Last 365 Days Men's Big 5 Leagues, UCL, UEL` `scouting_period`.

**Additional info:**
The issue is not reproducible with all the players. For example, with Dybala it works as expected:
```
data <- fb_player_scouting_report("https://fbref.com/en/players/e0921a4f/Paulo-Dybala", pos_versus="primary", league_comp_name="Serie A")
```

**Comment by SeriyBg** [comment]
Just an update: it seems that the data retrieved is actually correct. But the value set for the `scouting_period` field is wrong

**Comment by JaseZiv** [comment]
What version of `worldfootbalR` are you using?

**Comment by SeriyBg** [comment]
I'm using `0.6.4.0014` downloaded from CRAN

**Comment by JaseZiv** [comment]
Please make sure you're using the latest dev version from github. If the problem persists, please raise a fresh issue
