### ISSUE TITLE
fb_player_scouting_report() returns error

### ISSUE THREAD

**Issue by jtrain907** [JaseZiv/worldfootballR#361]
df <- fb_player_scouting_report("https://fbref.com/en/players/fdf3cb77/Vladimir-Coufal", pos_versus = "primary") returns 

Error in fb_player_scouting_report("https://fbref.com/en/players/fdf3cb77/Vladimir-Coufal",  : 
  Full scouting report not available for Vladimír Coufal

Error is for all players. Function was working last night and this morning, and suddenly stopped. Did an uninstall and reinstall of worldfootballR, on version 0.6.2.

**Comment by JaseZiv** [comment]
You will need to update to the latest dev version from github.

Install using `devtools::install_github("JaseZiv/worldfootballR")`, then restart your R session.
