### ISSUE TITLE
Argentina tier 1 2024 missing?

### ISSUE THREAD

**Issue by fine-lemur** [JaseZiv/worldfootballR#362]
---

Argentina tier 1 2024 missing?

```r
library(worldfootballR)
packageVersion("worldfootballR")

a <- worldfootballR::load_match_results(country = 'ARG', tier = '1st', gender = "M", season_end_year = 2024)
b <- worldfootballR::fb_match_results(country = 'ARG', tier = '1st', gender = "M", season_end_year = 2024)

sessionInfo()
```

(a) returns empty data frame
(b) returns Error in fb_match_results(country = 'ARG', tier = '1st', gender = "M", season_end_year = 2024): Data not available for the season(s) selected. 

previous seasons are fine. any suggestions?

**Comment by JaseZiv** [comment]
That's because it isn't yet available on FBRef:

<img width="630" alt="image" src="https://github.com/JaseZiv/worldfootballR/assets/31471783/12c72f18-e22d-4956-8412-e1a80a9a3eca">
