### ISSUE TITLE
USL 2023 data not loading

### ISSUE THREAD

**Issue by samspopguy** [JaseZiv/worldfootballR#366]
getting an error that data is not there for 2023 works for 2022 though was wondering if a lot of the functions for USL and 2023 doesn't work

```r
library(worldfootballR)
packageVersion("worldfootballR")

fb_season_team_stats(
  country = "USA",
  gender = "M",
  season_end_year = "2023",
  tier = "2nd",
  stat_type = "shooting"
)


sessionInfo()
```

the error i get is this
NOTE: Stat Type 'shooting' is not found for this league season. Check https://fbref.com/en/comps/73/USL-Championship-Stats to see if it exists.
data frame with 0 columns and 0 rows

and when i go to that page it looks like it has the correct table to get the info from

**Comment by JaseZiv** [comment]
Can you please confirm the output of `packageVersion("worldfootballR")`?

**Comment by samspopguy** [comment]
> Can you please confirm the output of `packageVersion("worldfootballR")`?

`> packageVersion("worldfootballR")
[1] ‘0.6.2’`

**Comment by JaseZiv** [comment]
You will need to update to the latest dev version using `devtools::install_github("JaseZiv/worldfootballR")`

**Comment by samspopguy** [comment]
updated to 
> packageVersion("worldfootballR")
[1] ‘0.6.5.3’

but still getting the same error

`fb_season_team_stats(
+   country = "USA",
+   gender = "M",
+   season_end_year = "2023",
+   tier = "2nd",
+   stat_type = "shooting"
+ )
NOTE: Stat Type 'shooting' is not found for this league season. Check https://fbref.com/en/comps/73/USL-Championship-Stats to see if it exists.
data frame with 0 columns and 0 rows`

**Comment by JaseZiv** [comment]
Ah ok cool. I'm thinking this could be because the 2024 link has become available in the last week. We have an automated process that runs weekly (and will run in less than 24 hours) so that should solve it then. Will report back once it's all sorted.

Thanks

**Comment by samspopguy** [comment]
ah, that makes sense with why the 2023 stuff isn't working but older stuff is with the season starting on the 9th they created the links for the new season.

**Comment by JaseZiv** [comment]
This has now resolved itself so will close the issue.

Feel free to raise a new one if you're still experiencing problems.
