### ISSUE TITLE
player_transfer_history failing for players who have been or will be without club

### ISSUE THREAD

**Issue by ChrisH1997** [JaseZiv/worldfootballR#37]
player_transfer_history is failing for players who have been without club or will be in the future because 'country_to' can't be found in these cases. 
`player_transfer_history("https://www.transfermarkt.com/sergio-aguero/profil/spieler/26399")
player_transfer_history("https://www.transfermarkt.com/christian-gentner/profil/spieler/19112")`

**Comment by JaseZiv** [comment]
Thanks for bringing this to my attention. Should be fixed with v0.3.0.1 just released so reinstall the package and all should be good.
