### ISSUE TITLE
Fotmob Get Season Stats Throwing Index Errors

### ISSUE THREAD

**Issue by Jeffreyjose29** [JaseZiv/worldfootballR#377]
Hi,

I have been working on a project to pull season statistics for the Indian Super League 2023/2024. I have tried used the fotmob_get_season_stats() function but it returns an error saying 

```r
Error in `map2()`:
ℹ In index: 1.
Caused by error in `pmap()`:
ℹ In index: 1.
Caused by error in `.fotmob_get_stat_and_season_options()`:
! Could not parse season ids from https://www.fotmob.com/leagues/9478/stats/super-league/teams.
Run `rlang::last_trace()` to see where the error occurred.
```

My function with parameter is as follows:

```r
library(worldfootballR)
packageVersion("worldfootballR")

fotmob_get_season_stats(
  country = "IND",
  league_id = 9478,
  season_name = "2023/2024",
  team_or_player = c("team"),
  stat_name = "Accurate crosses per match",
  #stat_league_name = league_name,
  cached = TRUE
)

sessionInfo()
```

I tried running the same code using the example Premier League function provided in the documentation and it still throws the same error. 

```r
library(worldfootballR)
packageVersion("worldfootballR")

fotmob_get_season_stats(
  country = "ENG",
  league_name = "Premier League",
  season_name = "2020/2021",
  stat_name = "Expected Goals",
  team_or_player = "team"
)

sessionInfo()
```

I hope this helps you to understand the problem but more than happy to elaborate.

Thanks!

**Comment by JaseZiv** [comment]
Fotmob functions haven't been supported for a number of version updates now. Have a read of the change log in `NEWS.md` for more details.

**Comment by Jeffreyjose29** [comment]
Hi,

Thank you for guiding me to that. I probably should have checked prior to asking. Much appreciated! :)
