### ISSUE TITLE
Incorrect Formation value for teams with Diamond Formation in get_match_lineups()

### ISSUE THREAD

**Issue by venkatanarayanan** [JaseZiv/worldfootballR#38]
<img width="642" alt="error" src="https://user-images.githubusercontent.com/20023133/120423806-c7346380-c388-11eb-9409-d6828115a6bb.PNG">

Code:
get_match_lineups("https://fbref.com/en/matches/75dd1359/Manchester-United-Arsenal-November-1-2020-Premier-League")

**Comment by JaseZiv** [comment]
This issue was occurring on Windows machines, which were bringing in the diamond symbol as a UTF-8 character string (u256), then getting all numbers in the formation string and pasting them together with a "-" separator. MacOS would bring these in to the environment as "..".
