### ISSUE TITLE
Could not find function "fb_league_stats"

### ISSUE THREAD

**Issue by JuanmaMN** [JaseZiv/worldfootballR#381]
Hi. I'm trying to run the fb_league_stats to get player stats like below but I'm getting the error that 

`  could not find function `"fb_league_stats"`

Has there been a recent issue with the function?

```r
prem_2020_player_shooting <- fb_league_stats(
  country = "ENG",
  gender = "M",
  season_end_year = 2020,
  tier = "1st",
  non_dom_league_url = NA,
  stat_type = "shooting",
  team_or_player = "player"
)
```

**Comment by JuanmaMN** [comment]
I've managed to get similar data by using `load_fb_big5_advanced_season_stats`. Are you able to advise the best way to get Champions League data for players?

**Comment by JaseZiv** [comment]
> Hi. I'm trying to run the fb_league_stats to get player stats like below but I'm getting the error that
> 
> ` could not find function`"fb_league_stats"`
> 
> Has there been a recent issue with the function?
> 
> ```r
> prem_2020_player_shooting <- fb_league_stats(
>   country = "ENG",
>   gender = "M",
>   season_end_year = 2020,
>   tier = "1st",
>   non_dom_league_url = NA,
>   stat_type = "shooting",
>   team_or_player = "player"
> )
> ```

What version of `worldfootballR` are you using?

**Comment by JuanmaMN** [comment]
I'm using ‘0.6.5.4’

**Comment by tonyelhabr** [comment]
Did you make sure to `library(worldfootballR)` before your code snippet?

```r
library(worldfootballR)
prem_2020_player_shooting <- fb_league_stats(
  country = "ENG",
  gender = "M",
  season_end_year = 2020,
  tier = "1st",
  non_dom_league_url = NA,
  stat_type = "shooting",
  team_or_player = "player"
)
```

or this

```r
prem_2020_player_shooting <- worldfootballR::fb_league_stats(
  country = "ENG",
  gender = "M",
  season_end_year = 2020,
  tier = "1st",
  non_dom_league_url = NA,
  stat_type = "shooting",
  team_or_player = "player"
)
```

**Comment by JuanmaMN** [comment]
Hello. Yes.  I uploaded the package beforehand

**Comment by tonyelhabr** [comment]
are you updating the package from CRAN with `install.packages('worldfootballR')`? while that's convenient, the version on CRAN isn't actually the latest version at the moment, so may have some issues. you'd need to run `remotes::install_github('JaseZiv/worldfootballR')` to get the latest version.

can you take a screenshot of what your RStudio looks like when you run this?

```r
packageVersion('worldfootballR') ## interested to see what this says
```

**Comment by JuanmaMN** [comment]
Great. Thanks a lot. My package version is [1] ‘0.6.5.4’

**Comment by JuanmaMN** [comment]
It's all running fine now
