### ISSUE TITLE
fb_advanced_match_stats not working Brazilian League

### ISSUE THREAD

**Issue by LuccaStochiero** [JaseZiv/worldfootballR#382]
Trying to get the advanced match stats of recent Brazilian League matches and its not working.

> fb_advanced_match_stats('https://fbref.com/en/matches/4a537b33/Juventude-Vitoria-June-11-2024-Serie-A', stat_type = 'summary', team_or_player = 'player')

Stats data not available for https://fbref.com/en/matches/4a537b33/Juventude-Vitoria-June-11-2024-Serie-A
data frame with 0 columns and 0 rows

**Comment by JaseZiv** [comment]
What version of `worldfootballR` are you using?

It works for me:

```
packageVersion("worldfootballR")
[1] ‘0.6.5.4’

aa <- worldfootballR::fb_advanced_match_stats('https://fbref.com/en/matches/4a537b33/Juventude-Vitoria-June-11-2024-Serie-A', stat_type = 'summary', team_or_player = 'player')

dplyr::glimpse(aa)

Rows: 32
Columns: 52
$ League             <chr> "Campeonato Brasileiro Série A", "Campeonato Brasileiro Série A", "Campeonato Brasileiro Série A", "Campeonato…
$ Match_Date         <chr> "2024-06-11", "2024-06-11", "2024-06-11", "2024-06-11", "2024-06-11", "2024-06-11", "2024-06-11", "2024-06-11"…
$ Matchweek          <chr> "Campeonato Brasileiro Série A (Matchweek 8)", "Campeonato Brasileiro Série A (Matchweek 8)", "Campeonato Bras…
$ Home_Team          <chr> "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juven…
$ Home_Formation     <chr> "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", …
$ Home_Score         <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
$ Home_xG            <dbl> 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, …
$ Home_Goals         <chr> "Rodrigo Sam · 34&rsquor;", "Rodrigo Sam · 34&rsquor;", "Rodrigo Sam · 34&rsquor;", "Rodrigo Sam · 34&rsquor;"…
$ Home_Yellow_Cards  <chr> "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", …
$ Home_Red_Cards     <chr> "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", …
$ Away_Team          <chr> "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", …
$ Away_Formation     <chr> "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", …
$ Away_Score         <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
$ Away_xG            <dbl> 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, …
$ Away_Goals         <chr> "Willian · 42&rsquor;", "Willian · 42&rsquor;", "Willian · 42&rsquor;", "Willian · 42&rsquor;", "Willian · 42&…
$ Away_Yellow_Cards  <chr> "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", …
$ Away_Red_Cards     <chr> "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", …
$ Game_URL           <chr> "https://fbref.com/en/matches/4a537b33/Juventude-Vitoria-June-11-2024-Serie-A", "https://fbref.com/en/matches/…
$ Team               <chr> "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juven…
$ Home_Away          <chr> "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home"…
$ Player             <chr> "Erick", "Gilberto", "Marcelinho", "Rildo", "Lucas Barbosa", "Ruan", "Nenê", "Luis Mandaca", "Caíque de Jesus …
$ Player_Href        <chr> "/en/players/f50ae991/Erick", "/en/players/5da22685/Gilberto", "/en/players/c158eb1d/Marcelinho", "/en/players…
$ Player_Num         <dbl> 7, 9, 11, 37, 21, 29, 10, 44, 95, 16, 28, 34, 4, 14, 12, 1, 9, 12, 11, 5, 15, 17, 29, 30, 10, 8, 31, 16, 4, 13…
$ Nation             <chr> "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA"…
$ Pos                <chr> "FW", "FW", "LW", "LW", "RW", "RW", "AM", "AM", "DM", "DM", "LB", "CB", "CB", "RB", "RB", "GK", "FW", "FW", "L…
$ Age                <chr> "27-160", "35-006", "21-183", "24-142", "23-110", "19-039", "42-328", "22-253", "28-245", "30-286", "34-293", …
$ Min                <dbl> 55, 35, 55, 35, 86, 4, 77, 13, 90, 90, 90, 90, 90, 77, 13, 90, 64, 26, 45, 45, 45, 45, 90, 83, 7, 63, 27, 90, …
$ Gls                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ Ast                <dbl> 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0
$ PK                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ PKatt              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ Sh                 <dbl> 1, 0, 2, 1, 1, 0, 0, 1, 0, 2, 0, 3, 0, 1, 0, 0, 1, 0, 0, 2, 0, 1, 3, 4, 0, 0, 0, 2, 0, 2, 3, 0
$ SoT                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0
$ CrdY               <dbl> 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1
$ CrdR               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ Touches            <dbl> 15, 11, 24, 17, 41, 4, 40, 13, 67, 67, 78, 88, 97, 60, 18, 33, 21, 7, 14, 17, 15, 21, 39, 43, 2, 30, 7, 59, 63…
$ Tkl                <dbl> 0, 0, 0, 0, 2, 0, 0, 0, 4, 5, 3, 2, 0, 2, 1, 0, 0, 0, 0, 3, 1, 2, 3, 1, 0, 0, 1, 0, 1, 0, 7, 0
$ Int                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0
$ Blocks             <dbl> 0, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 5, 0
$ xG_Expected        <dbl> 0.2, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, …
$ npxG_Expected      <dbl> 0.2, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, …
$ xAG_Expected       <dbl> 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, …
$ SCA_SCA            <dbl> 1, 0, 2, 0, 2, 0, 7, 0, 1, 4, 1, 2, 0, 1, 0, 0, 2, 0, 1, 5, 0, 3, 5, 5, 0, 0, 0, 4, 0, 0, 4, 0
$ GCA_SCA            <dbl> 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0
$ Cmp_Passes         <dbl> 7, 5, 8, 5, 23, 3, 22, 6, 52, 49, 57, 69, 82, 36, 11, 29, 8, 3, 9, 7, 14, 8, 21, 24, 1, 24, 2, 39, 46, 33, 36,…
$ Att_Passes         <dbl> 13, 9, 15, 9, 29, 3, 38, 10, 59, 56, 70, 75, 88, 53, 14, 31, 11, 5, 13, 10, 15, 11, 28, 31, 2, 28, 2, 49, 55, …
$ Cmp_percent_Passes <dbl> 53.8, 55.6, 53.3, 55.6, 79.3, 100.0, 57.9, 60.0, 88.1, 87.5, 81.4, 92.0, 93.2, 67.9, 78.6, 93.5, 72.7, 60.0, 6…
$ PrgP_Passes        <dbl> 0, 1, 1, 0, 3, 0, 4, 1, 6, 8, 5, 3, 8, 4, 0, 0, 1, 0, 2, 0, 4, 1, 2, 3, 0, 1, 0, 2, 0, 2, 6, 0
$ Carries_Carries    <dbl> 6, 3, 12, 10, 22, 2, 22, 5, 29, 25, 32, 47, 58, 23, 7, 15, 13, 2, 13, 10, 12, 15, 23, 31, 1, 19, 3, 34, 39, 31…
$ PrgC_Carries       <dbl> 0, 0, 0, 1, 0, 0, 2, 1, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0
$ Att_Take_Ons       <dbl> 0, 1, 3, 5, 0, 0, 0, 3, 3, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 3, 1, 3, 0, 0, 1, 1, 0, 0, 2, 0
$ Succ_Take_Ons      <dbl> 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0
```

**Comment by scottkaplan1112** [comment]
Similar issue for me. I verified I had the up to date package number. It seems like it's not working for any link I put in.

```r
> packageVersion("worldfootballR")
[1] ‘0.6.5.4’

> aa <- worldfootballR::fb_advanced_match_stats('https://fbref.com/en/matches/4a537b33/Juventude-Vitoria-June-11-2024-Serie-A', stat_type = 'summary', team_or_player = 'player')
Stats data not available for https://fbref.com/en/matches/4a537b33/Juventude-Vitoria-June-11-2024-Serie-A

> dplyr::glimpse(aa)
Rows: 0
Columns: 0
```

**Comment by scottkaplan1112** [comment]
It seems like it could be due to exceeding a certain number of calls on the API in a certain timeframe.

**Comment by tonyelhabr** [comment]
> What version of `worldfootballR` are you using?
> 
> It works for me:
> 
> ```
> packageVersion("worldfootballR")
> [1] ‘0.6.5.4’
> 
> aa <- worldfootballR::fb_advanced_match_stats('https://fbref.com/en/matches/4a537b33/Juventude-Vitoria-June-11-2024-Serie-A', stat_type = 'summary', team_or_player = 'player')
> 
> dplyr::glimpse(aa)
> 
> Rows: 32
> Columns: 52
> $ League             <chr> "Campeonato Brasileiro Série A", "Campeonato Brasileiro Série A", "Campeonato Brasileiro Série A", "Campeonato…
> $ Match_Date         <chr> "2024-06-11", "2024-06-11", "2024-06-11", "2024-06-11", "2024-06-11", "2024-06-11", "2024-06-11", "2024-06-11"…
> $ Matchweek          <chr> "Campeonato Brasileiro Série A (Matchweek 8)", "Campeonato Brasileiro Série A (Matchweek 8)", "Campeonato Bras…
> $ Home_Team          <chr> "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juven…
> $ Home_Formation     <chr> "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", "4-2-3-1", …
> $ Home_Score         <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
> $ Home_xG            <dbl> 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, …
> $ Home_Goals         <chr> "Rodrigo Sam · 34&rsquor;", "Rodrigo Sam · 34&rsquor;", "Rodrigo Sam · 34&rsquor;", "Rodrigo Sam · 34&rsquor;"…
> $ Home_Yellow_Cards  <chr> "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", …
> $ Home_Red_Cards     <chr> "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", …
> $ Away_Team          <chr> "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", "Vitória", …
> $ Away_Formation     <chr> "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", "4-1-4-1", …
> $ Away_Score         <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
> $ Away_xG            <dbl> 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, …
> $ Away_Goals         <chr> "Willian · 42&rsquor;", "Willian · 42&rsquor;", "Willian · 42&rsquor;", "Willian · 42&rsquor;", "Willian · 42&…
> $ Away_Yellow_Cards  <chr> "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", "4", …
> $ Away_Red_Cards     <chr> "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", …
> $ Game_URL           <chr> "https://fbref.com/en/matches/4a537b33/Juventude-Vitoria-June-11-2024-Serie-A", "https://fbref.com/en/matches/…
> $ Team               <chr> "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juventude", "Juven…
> $ Home_Away          <chr> "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home", "Home"…
> $ Player             <chr> "Erick", "Gilberto", "Marcelinho", "Rildo", "Lucas Barbosa", "Ruan", "Nenê", "Luis Mandaca", "Caíque de Jesus …
> $ Player_Href        <chr> "/en/players/f50ae991/Erick", "/en/players/5da22685/Gilberto", "/en/players/c158eb1d/Marcelinho", "/en/players…
> $ Player_Num         <dbl> 7, 9, 11, 37, 21, 29, 10, 44, 95, 16, 28, 34, 4, 14, 12, 1, 9, 12, 11, 5, 15, 17, 29, 30, 10, 8, 31, 16, 4, 13…
> $ Nation             <chr> "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA", "BRA"…
> $ Pos                <chr> "FW", "FW", "LW", "LW", "RW", "RW", "AM", "AM", "DM", "DM", "LB", "CB", "CB", "RB", "RB", "GK", "FW", "FW", "L…
> $ Age                <chr> "27-160", "35-006", "21-183", "24-142", "23-110", "19-039", "42-328", "22-253", "28-245", "30-286", "34-293", …
> $ Min                <dbl> 55, 35, 55, 35, 86, 4, 77, 13, 90, 90, 90, 90, 90, 77, 13, 90, 64, 26, 45, 45, 45, 45, 90, 83, 7, 63, 27, 90, …
> $ Gls                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
> $ Ast                <dbl> 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0
> $ PK                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
> $ PKatt              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
> $ Sh                 <dbl> 1, 0, 2, 1, 1, 0, 0, 1, 0, 2, 0, 3, 0, 1, 0, 0, 1, 0, 0, 2, 0, 1, 3, 4, 0, 0, 0, 2, 0, 2, 3, 0
> $ SoT                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0
> $ CrdY               <dbl> 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1
> $ CrdR               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
> $ Touches            <dbl> 15, 11, 24, 17, 41, 4, 40, 13, 67, 67, 78, 88, 97, 60, 18, 33, 21, 7, 14, 17, 15, 21, 39, 43, 2, 30, 7, 59, 63…
> $ Tkl                <dbl> 0, 0, 0, 0, 2, 0, 0, 0, 4, 5, 3, 2, 0, 2, 1, 0, 0, 0, 0, 3, 1, 2, 3, 1, 0, 0, 1, 0, 1, 0, 7, 0
> $ Int                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0
> $ Blocks             <dbl> 0, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 5, 0
> $ xG_Expected        <dbl> 0.2, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, …
> $ npxG_Expected      <dbl> 0.2, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, …
> $ xAG_Expected       <dbl> 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, …
> $ SCA_SCA            <dbl> 1, 0, 2, 0, 2, 0, 7, 0, 1, 4, 1, 2, 0, 1, 0, 0, 2, 0, 1, 5, 0, 3, 5, 5, 0, 0, 0, 4, 0, 0, 4, 0
> $ GCA_SCA            <dbl> 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0
> $ Cmp_Passes         <dbl> 7, 5, 8, 5, 23, 3, 22, 6, 52, 49, 57, 69, 82, 36, 11, 29, 8, 3, 9, 7, 14, 8, 21, 24, 1, 24, 2, 39, 46, 33, 36,…
> $ Att_Passes         <dbl> 13, 9, 15, 9, 29, 3, 38, 10, 59, 56, 70, 75, 88, 53, 14, 31, 11, 5, 13, 10, 15, 11, 28, 31, 2, 28, 2, 49, 55, …
> $ Cmp_percent_Passes <dbl> 53.8, 55.6, 53.3, 55.6, 79.3, 100.0, 57.9, 60.0, 88.1, 87.5, 81.4, 92.0, 93.2, 67.9, 78.6, 93.5, 72.7, 60.0, 6…
> $ PrgP_Passes        <dbl> 0, 1, 1, 0, 3, 0, 4, 1, 6, 8, 5, 3, 8, 4, 0, 0, 1, 0, 2, 0, 4, 1, 2, 3, 0, 1, 0, 2, 0, 2, 6, 0
> $ Carries_Carries    <dbl> 6, 3, 12, 10, 22, 2, 22, 5, 29, 25, 32, 47, 58, 23, 7, 15, 13, 2, 13, 10, 12, 15, 23, 31, 1, 19, 3, 34, 39, 31…
> $ PrgC_Carries       <dbl> 0, 0, 0, 1, 0, 0, 2, 1, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0
> $ Att_Take_Ons       <dbl> 0, 1, 3, 5, 0, 0, 0, 3, 3, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 3, 1, 3, 0, 0, 1, 1, 0, 0, 2, 0
> $ Succ_Take_Ons      <dbl> 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0
> ```

This also works fine for me. (I'm on a slightly older version of the package, 0.6.5.1.)

If the issue were due to hitting the API call rate limit, I think you'll see a `403` error.

What I think may be going on is just temporary slow refreshes on fbref's server-side. Like, for example, when trying to navigate to `https://fbref.com/en/matches/e3c3ddf0/Arsenal-Leicester-City-August-11-2017-Premier-League` this morning (just a random old match), I hit a blank page in my browser. (I wish I had taken a screenshot.)But trying it now, the page is populated. I've observed this kind of thing a few times (even with different browsers), and all seemed to be random.

**Comment by scottkaplan1112** [comment]
I had some success increasing the time interval between calls to the server. May be worth a shot.
