### ISSUE TITLE
fb_match_report and rb_match_summary for usl games

### ISSUE THREAD

**Issue by samspopguy** [JaseZiv/worldfootballR#393]
---

The following code was working for me but stopped like a month or so again
the fb_match_summary returns data until like march 26th but nothing after that just says 

Match Summary not available for https://fbref.com/en/matches/de3bcb54/North-Carolina-FC-Tampa-Bay-Rowdies-March-23-2024-USL-Championship

and match report just says
https://fbref.com/en/matches/0dedcceb/El-Paso-Locomotive-Oakland-Roots-April-13-2024-USL-Championship is not available

‘0.6.2’ is the version im running

```r
library(worldfootballR)
packageVersion("worldfootballR")

match_usl_2024 <- fb_match_urls(country = "USA", gender = "M", season_end_year = 2024, tier = "2nd")
usl_2024 <- fb_match_summary(match_url = match_usl_2024)
usl_2024_final<-fb_match_report(match_url = match_usl_2024)

sessionInfo()
```

**Comment by JaseZiv** [comment]
Your version is extremely out of date.

Only install the dev version from github as the CRAN version is not being updated.

**Comment by samspopguy** [comment]
oh I swear I looked at that and was like yes that's update to at .0.6.5
