### ISSUE TITLE
tm_league_team_urls() giving an error

### ISSUE THREAD

**Issue by wrahool** [JaseZiv/worldfootballR#40]
When I run

`team_urls <- tm_league_team_urls(country_name = "England", start_year = 2020)`

 I get the following error:

`Error in nrow(meta_df_seasons) : object 'meta_df_seasons' not found`

**Comment by JaseZiv** [comment]
Can you please also include the code that caused the error when raising an issue?

**Comment by wrahool** [comment]
Sorry. I updated the issue with the line of code (it's the same code as the one you posted in your comment)

![image](https://user-images.githubusercontent.com/8686922/121354713-ba53d900-c961-11eb-8616-593fd3414410.png)

**Comment by JaseZiv** [comment]
Interesting. What version of R are you using and what OS?

**Comment by wrahool** [comment]
4.0.5, Windows 10.

**Comment by JaseZiv** [comment]
I've tested this in R4.0.5 on both Windows and MacOS and can't recreate this error. Are you still experiencing it?

**Comment by JaseZiv** [comment]
Marking this closed. Please reopen if you're still experiencing issues
