### ISSUE TITLE
xg data errors using load_fb_match_shooting

### ISSUE THREAD

**Issue by 1Colin11** [JaseZiv/worldfootballR#404]
---
For example,
```r
library(tidyverse)
library(worldfootballR)

shot_times =
  load_fb_match_shooting(
    country = "ENG",
    gender = "M",
    tier = "1st"
  ) %>%
  janitor::clean_names()

shot_times %>%
  filter(match_url == "https://fbref.com/en/matches/29e4d6ac/Liverpool-Burnley-February-10-2024-Premier-League", player == "David Datro Fofana") %>%
  View
```
gives two rows of 0.09 and 0.08 xg. 
If you go to the url, in the shots section, his two shots are recorded as 0.47 and 0.36 xg.
There are many examples of this. I have not checked other leagues.
Is it possible the repo could be correctly updated?
Many thanks for the helpful package.

**Comment by JaseZiv** [comment]
Not sure what's happened here... can you provide a few more examples to give me a sense of where to start? I've done a spot check of some La Liga matches and they all look fine.

The processing to enable rapid loading of data is pretty challenging, and needing to backfill potentially many seasons worth of games will be even more so...

**Comment by tonyelhabr** [comment]
i wonder if this may be due to fbref updates to the shot log after we have scraped the data? i think Opta often makes adjustments a day or so after a match is completed.

if this were the case, then maybe we should have the scraper wait ~5 days before attempting to scrape a given match week. it seems sort of difficult to confirm whether this is actually the case though.

**Comment by JaseZiv** [comment]
Yeah I think that might be the case @tonyelhabr... The possible solution you've proposed seems like a great idea... I've also been wondering about the whole loading functionality, but maybe we take that discussion offline.

**Comment by tonyelhabr** [comment]
i'm working on a solution. i'll give an update (likely this week) on the implementation

**Comment by tonyelhabr** [comment]
> i'm working on a solution. i'll give an update (likely this week) on the implementation

i've updated the big 5 shooting data in `worldfootballR_data`, which changes the data pulled in by `load_fb_match_shooting`. i simply re-scraped all shot logs for this season--i only updated the scraper to run daily before the beginning of this season--and overwrote the data for this season.

the implementation for the future--wait 3 days before scraping a match's shot logs. i wish we could more reasonably detect a team's next match, then scrape up till the preceding match, but it's not quite straightforward to do that with our current functions / without creating a bunch of custom logic. so waiting a few days before scraping seems like a reasonable and maintainable solution.
