### ISSUE TITLE
Problem with load_fb_advanced_match_stats summary stats

### ISSUE THREAD

**Issue by sgrassie** [JaseZiv/worldfootballR#406]
Trying to get the advanced matches stats from `load_fb_advanced_match_stats` fails with:

`Data not loaded. Please check parameters.`

```r
library(worldfootballR)
packageVersion("worldfootballR")
match_stats_summary <- load_fb_advanced_match_stats(country = "ENG", gender = "M", tier = "1st", stat_type="summary", team_or_player = "player")

sessionInfo()
```

**Comment by tonyelhabr** [comment]
Resolved now. I think this may happen rarely when the GitHub Action times out while writing to the RDS file. [I've added some logic](https://github.com/JaseZiv/worldfootballR_data/commit/c5913eecf8bdcef9ebe427d3c72393cf78c3bcb1) to fall-back to reading from the CSV file on the next workflow run, after which point the RDS file will be regenerated.
