### ISSUE TITLE
get_player_market_values failing for seasons before 2020/21

### ISSUE THREAD

**Issue by ChrisH1997** [JaseZiv/worldfootballR#41]
Since the last update on `get_player_market_values` it is failing for seasons before 2020/21.
Error message: `Column "joined_from" not found in ".data"`
`get_player_market_values(country_name = "England", start_year = 2020)` works,
`get_player_market_values(country_name = "England", start_year = 2019)` doesn't. Also tested for some other countries.
Tested with R version 4.0.5.

**Comment by JaseZiv** [comment]
I think I know what is going on here. Now that the function returns additional columns, the index of some of these is thrown out, because previous years have an additional column called  `Current club`, where current seasons don't.

I will sort this over the next day.

Thanks for identifying it.

**Comment by JaseZiv** [comment]
This should be fixed as of version 0.3.1.1
