### ISSUE TITLE
Error obtaining lineups pre 2015

### ISSUE THREAD

**Issue by AndreasDane** [JaseZiv/worldfootballR#44]
I've been getting "Error in `[.data.frame`(lineup, , 1) : undefined columns selected" when I've tried to get PL lineups from around the 2015 season and before. As far as I can tell the data does still exist in fbref for these seasons. 

```
match_urls <- get_match_urls(country = "ENG", gender = "M", season_end_year = 2003)
[1] "Scraping match URLs"
[1] "Match URLs scrape completed"
> match_lineups <- get_match_lineups(match_url = match_urls)
[1] "Scraping lineups"
Error in `[.data.frame`(lineup, , 1) : undefined columns selected
>
```

**Comment by JaseZiv** [comment]
For the season you've listed in the MRE, there are no lineups available on FBref for that season (that I've found anyway):
![image](https://user-images.githubusercontent.com/31471783/127571843-3f743dbc-d252-4d36-bcfe-c881d852dd48.png)

When I look at the 2013-14 season, this is also true: 
![image](https://user-images.githubusercontent.com/31471783/127572002-936e4f0b-3c07-49c8-9e54-f38fc8d78533.png)

The lineups data comes from this section on a page, that only began in the EPL for the 2015-16 season and beyond:
![image](https://user-images.githubusercontent.com/31471783/127572446-158a7d9e-c4da-452a-996e-cd759fab4525.png)


Let me know if you're seeing something different to this.

**Comment by AndreasDane** [comment]
Oh okay. I didn't know the data was being scraped from those match diagrams and not the tables below which explains why. 

![Screenshot_20210730-071300](https://user-images.githubusercontent.com/39284864/127609145-2fa6a943-c475-44b9-b617-e6d1ef466a9f.png)

**Comment by JaseZiv** [comment]
Yeah not from there asI wanted to include formations in the results from that function.

Will mark this closed for now.
