### ISSUE TITLE
differentiate between free transfers and unknown fees in player_transfer_history()

### ISSUE THREAD

**Issue by ChrisH1997** [JaseZiv/worldfootballR#45]
Is there a chance, that you could change the transfer value in player_transfer_history() to "0" for free transfers? That would be helpful, to know if a player was transferred for free or transfermarkt.com just has no information on the fee.

**Comment by JaseZiv** [comment]
Good suggestion. Will try to fix this within the next week or so.

Thanks

**Comment by JaseZiv** [comment]
I've resolved this issue with commit [9229e58](https://github.com/JaseZiv/worldfootballR/commit/9229e585b71ea9f558b7b297f917465efb109e84)
