### ISSUE TITLE
get_match_summary --- Arguments imply differing number of rows

### ISSUE THREAD

**Issue by AndreasDane** [JaseZiv/worldfootballR#46]
I've been able to retrieve EPL match summaries up to 2013/2014 perfectly, however when I was trying to retrieve 2012/2013, I ran into this: 

`> match_urls <- get_match_urls(country = "ENG", gender = "M", season_end_year = 2013)
[1] "Scraping match URLs"
[1] "Match URLs scrape completed"
> match_summaries <- get_match_summary(match_url = match_urls)
[==============================================================>-------------------------------------------------]  56%Error in data.frame(Team = Home_Team, Home_Away = "Home", events_string = events_home) : 
  arguments imply differing number of rows: 1, 0`

Similarly for 2011/2012:

`> match_urls <- get_match_urls(country = "ENG", gender = "M", season_end_year = 2012)
[1] "Scraping match URLs"
[1] "Match URLs scrape completed"
> match_summaries <- get_match_summary(match_url = match_urls)
[==========================================================================================>---------------------]  81%Error in data.frame(Team = Home_Team, Home_Away = "Home", events_string = events_home) : 
  arguments imply differing number of rows: 1, 0

I took a brief look at the EPL fixtures for 2011/2012, going to where the 81% mark would roughly be and didn't find any difference in how FBref is missing or match summary data. Any explanation would be appreciated as to why this is happening.

**Comment by JaseZiv** [comment]
This one appears to be an issue - QPR didn't have any recorded actions so it's causing the scraper to break... I will push an update in the next couple of days to solve for this. In the meantime if you're desperate, you can always loop through each match_url and have some error handling.

Let me know if you need a hand with that.

Thanks for identifying this.

https://fbref.com/en/matches/a52210f1/Queens-Park-Rangers-Tottenham-Hotspur-January-12-2013-Premier-League

![image](https://user-images.githubusercontent.com/31471783/128102569-d642d3c4-af1e-4853-8b40-f958d63d4c61.png)

**Comment by JaseZiv** [comment]
This has now been fixed with commit [3ac5a23](https://github.com/JaseZiv/worldfootballR/commit/3ac5a2378fa8fd6a6edd52d2757c1fad601b9476)
