### ISSUE TITLE
Actual transfer date (or at least window) in transfermarkt data

### ISSUE THREAD

**Issue by birinoah** [JaseZiv/worldfootballR#49]
Would be useful for some analysis I'm doing. It's pretty annoying though because it doesn't look like transfermarkt actually displays that info on any of the transfer pages, just on the individual player pages. If anyone has suggestions for how to do this, i'm happy to work on the implementation myself.

**Comment by JaseZiv** [comment]
Yeah I can't find the transfer date anywhere in the html of the team transfer pages... Happy if someone wants to look further and point me in the right direction.

As you say, you can get the actual transfer date for each individual player though using the below:

```kovacic_transfer_history <- player_transfer_history(player_urls = "https://www.transfermarkt.com/mateo-kovacic/profil/spieler/51471")```

**Comment by birinoah** [comment]
I looked around a bunch more and found this style of page which I think is actually a better way of pulling the data for what I want (basically want to run analysis on "all transfers"). I'm new to this but been reading your scraper code that originally did this, think I should be able to write up a scraper for what I want. Happy to try and incorporate it into the repo if you'd like, or just keep it separate.

https://www.transfermarkt.com/chelsea-fc/transfers/verein/631/saison_id/2015/pos//detailpos/0/w_s//plus/1#zugaenge

**Comment by birinoah** [comment]
Actually that only works for the currently open transfer window... argh. Okay fine I'll go through the player pages.

**Comment by JaseZiv** [comment]
Keep an eye on any changes and if they change the site, I'll build it in to the function.

Thanks
