### ISSUE TITLE
get_match_urls() gets stuck on COVID postponed games

### ISSUE THREAD

**Issue by mimburgi** [JaseZiv/worldfootballR#55]
For example: 

`get_match_urls(country = "FRA", gender = "M", season_end_year = 2020, tier="1st") %>% get_match_lineups()`

gets to 74% and then returns

`Error in `[.data.frame`(lineup, , 1) : undefined columns selected`

I've tried troubleshooting by looping through each url and it seems like it's for games that got postponed due to COVID - they have an assigned URL but no lineups listed. I stuck a tryCatch in the manual loop to get by these but that's probably a bad blanket solution.

**Comment by JaseZiv** [comment]
Great pickup. I will work on a fix for this.

Do you think an appropriate solution for these (hopefully rare) cases would be to just have no mention of the game, or create a blank row with some sort or match metadata?

**Comment by mimburgi** [comment]
Personally I'd just leave them out of whatever the resulting function like get_match_lineups returns, if there's any kind of blank metadata in there you'd have to filter it out afterwards in most cases. I don't know what use having knowledge of the blank matches would be, but that doesn't mean there isn't one I guess. Maybe include_empty_matches=F as an argument in get_match_urls() to automatically filter these from the start, then users can switch it to T if they want to include them for some reason? I'm not sure that's worth the work/complexity.

Thank you for all the work you put into this!

**Comment by JaseZiv** [comment]
I agree - it'll get too confusing keeping the missing games in there. Pushing an update in a few minutes.

**Comment by JaseZiv** [comment]
Closing with commit https://github.com/JaseZiv/worldfootballR/commit/c60c5d1571c0858a698d29c9274668ff8a94f863
