### ISSUE TITLE
Encoding issues on Windows for player_dictionary_mapping()

### ISSUE THREAD

**Issue by mimburgi** [JaseZiv/worldfootballR#56]
Player names get returned like "Ã–mer Toprak". Specifying UTF-8 encoding explicitly within read.csv() in the function didn't work for me. Changing to readr::read_csv() with no additional arguments seems to solve the problem, like this:

`function () 
{
  players_mapped <- readr::read_csv("https://github.com/JaseZiv/worldfootballR_data/raw/master/raw-data/fbref-tm-player-mapping/output/fbref_to_tm_mapping.csv")
  return(players_mapped)
}
`

**Comment by JaseZiv** [comment]
Thanks for the suggestion! Will make a fix over the next 24 hours.

**Comment by JaseZiv** [comment]
Closing with commit https://github.com/JaseZiv/worldfootballR/commit/c6a6d951877009df6945e57783f65bc02691aed4
