### ISSUE TITLE
`tm_player_bio()` throws error

### ISSUE THREAD

**Issue by mca91** [JaseZiv/worldfootballR#57]
Hi Jason,

great package! Would have saved me a lot of time and work if I had learned about it earlier! :)

I just went through the vignette and tried a few of the examples. It seems to me that there is a (dplyr related) bug in `tm_player_bio()`:

Running

`hazard_bio <- tm_player_bio(player_url = "https://www.transfermarkt.com/eden-hazard/profil/spieler/50202")`

gives me

```
Error: Problem with `filter()` input `..1`.
Input `..1` is `!stringr::str_detect(.data$X1, "Social-Media")`.
Column `X1` not found in `.data`
Run `rlang::last_error()` to see where the error occurred.
```

Any ideas?

Best,
Martin

**Comment by JaseZiv** [comment]
Glad the package helps!

It appears something may have changed in the html. I'll have to investigate this and try to fix asap.

Thanks for picking this up!

**Comment by JaseZiv** [comment]
@mca91 This should be fixed now. Reinstall the package and let me know if there's any issues moving forward.

Thanks for picking it up.

**Comment by mca91** [comment]
I just tested it – works fine now, thanks!
