### ISSUE TITLE
Function for player injury history from Transfermarkt

### ISSUE THREAD

**Issue by OTStats** [JaseZiv/worldfootballR#58]
Extract injury history from player's Transfermarkt profile. Attributes include: season, injury, from (start date), until (end date), days (injured), games missed.

Example: https://www.transfermarkt.us/cristiano-ronaldo/verletzungen/spieler/8198/plus/1

**Comment by JaseZiv** [comment]
Thanks for the suggestion @OTStats!

The issue with this request is that without browser automation (Selenium), I can only scrape the first page of results... would this make it less than useful if the data returned is an incomplete injury history for players?
