### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by chrisask110** [JaseZiv/worldfootballR#59]
I'm having trouble with the get_player_market_values function to get player valuations from transfermarkt. Every time i try to use the function i get the message "**SSL certificate problem: certificate has expired**". I don't know if that is generel problem or that I am the only having this problem.

**Comment by JaseZiv** [comment]
Hi @chrisask110, I couldn't recreate that error so I'll need some more info from you.

Can you please provide the code you're using that's leading to errors, the OS, version of the package, etc?

Thanks

**Comment by steodose** [comment]
Hi @chrisask110 I'm wondering if you were able to resolve your "SSL certificate problem: certificate has expired" issue? I've come across the same thing when using the transfermarkt scraping functions (as well as when trying to scrape a few other websites). I suspect this is a local issue driven by certificate expirations, so I'm wondering what steps you specifically took to resolve? Those links @JaseZiv posted above are really helpful for context but not sure how to solve it exactly. Thanks!

I don't think it matters much in this case but:
I'm using macOS High Sierra version 10.13.4
R version 3.6.3
worldfootballR_0.3.5.3
