### ISSUE TITLE
Understat functions - Column `isResult` not found in `.data`

### ISSUE THREAD

**Issue by f33dy0urhe4d-VM** [JaseZiv/worldfootballR#60]
I'm having trouble retrieving data from Understat. In particular:

`> understat_league_match_results(league = "EPL", season_start_year = 2020)
Scraping match results data for EPL 2020 season. Please acknowledge understat.com as the data source
Error: Problem with `filter()` input `..1`.
ℹ Input `..1` is `isResult`.
x Column `isResult` not found in `.data`
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/dplyr_error>
Problem with `filter()` input `..1`.
ℹ Input `..1` is `isResult`.
x Column `isResult` not found in `.data`
Backtrace:
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/dplyr_error>
Problem with `filter()` input `..1`.
ℹ Input `..1` is `isResult`.
x Column `isResult` not found in `.data`
Backtrace:
     █
  1. ├─worldfootballR::understat_league_match_results(...)
  2. │ └─`%>%`(...)
  3. ├─dplyr::filter(., .data$isResult)
  4. ├─dplyr:::filter.data.frame(., .data$isResult)
  5. │ └─dplyr:::filter_rows(.data, ..., caller_env = caller_env())
  6. │   ├─base::withCallingHandlers(...)
  7. │   └─mask$eval_all_filter(dots, env_filter)
  8. ├─isResult
  9. ├─rlang:::`$.rlang_data_pronoun`(.data, isResult)
 10. │ └─rlang:::data_pronoun_get(x, nm)
 11. ├─rlang:::abort_data_pronoun(x)
 12. │ └─rlang::abort(msg, "rlang_error_data_pronoun_not_found")
 13. │   └─rlang:::signal_abort(cnd)
 14. │     └─base::signalCondition(cnd)
 15. └─(function (e) ...`

worldfootballR version: 0.3.5.3
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)

I face the same exact error when using understat_league_season_shots and understat_team_season_shots functions. Am I doing anything wrong? Any suggestion on how to fix this would be appreciated. thanks!

**Comment by JaseZiv** [comment]
Can you please  let me know if this issue persists. I have tested and can't recreate the issue, so will mark this closed for now.
