### ISSUE TITLE
Error getting match results with FotMob

### ISSUE THREAD

**Issue by Jes-Lop** [JaseZiv/worldfootballR#64]
Hello. When I try to use this script with the new functionality to scrap FotMob

`  details <- fotmob_get_match_details(match_ids)`
 
I get the following result

`Error in fotmob_get_match_details(match_ids) : 
  function "fotmob_get_match_details" could not be found.`

**Comment by JaseZiv** [comment]
Hi there,

Unfortunately FotMob have denied permission to use data from their site so functions getting data from them have been taken out of the library.

Really sorry.

Thanks
