### ISSUE TITLE
tm_league_team_urls function not working

### ISSUE THREAD

**Issue by HaugeEmil** [JaseZiv/worldfootballR#67]
I am having trouble using the tm_league_team_urls function to get a list of URLs for each team in a given season.  For simplicity, I run the following code:

> library(worldfootballR)
> team_urls <- tm_league_team_urls(country_name = "England", start_year = 2020)
> team_urls

team_urls have then stored a single URL: "https://transfermarkt.com". I have tried to use league_url argument as well, but it gives the same result.

This is a new issue for me, as I was having no trouble getting the team URLs last week.

**Comment by JaseZiv** [comment]
With the release of v0.4.2, this issue (and other transfermarkt functions) has been resolved.

Please reopen another issue if you're experiencing any other errors.
