### ISSUE TITLE
Function: `understat_league_match_results`

### ISSUE THREAD

**Issue by laurasimoes** [JaseZiv/worldfootballR#69]
When I set `understat_league_match_results(league = "La liga",season_start_year = '2018')` I only have the output for season 2021.

I change `season_start_year `argument to `2019` for example, and it keeps send `2021`season.

**Comment by JaseZiv** [comment]
Reopening this issue as it still exists, albeit slightly differently. The data being returned by the function is in fact for the season selected, although the `season` column is always returning the current season.

Will fix this in a new patch to be released in the next day or so

**Comment by JaseZiv** [comment]
Fixed in commit 6103895
