### ISSUE TITLE
PROBLEMS WITH ITALIAN PLAYERS

### ISSUE THREAD

**Issue by GermanLUD** [JaseZiv/worldfootballR#73]
Hello, 
when trying to scrape the statistics of the Italian players I get the following error. 
> ESTANDARDJUGADORES <- fb_team_player_stats(team_urls= ITA, stat_type= "standard")
Error: Problem with `mutate()` column `PlayerURL`.                                                                    
ℹ `PlayerURL = player_urls`.
ℹ `PlayerURL` must be size 48 or 1, not 47.
Am I doing something mine?
thank

**Comment by JaseZiv** [comment]
I can't seem to recreate the issue you're having... Can you please expand on the example you gave, for instance, provide the values for `ITA` that you have passed to the `team_urls` argument, also give the version of `worldfootbalR` you have installed and sessionInfo, etc.

On the most recent version of `worldfootballR`(0.4.6.1 GitHub version), the below code returns results as expected:

```
library(worldfootballR)

league <- fb_league_urls(country = "ITA", gender = "M", season_end_year = 2022)
teams <- fb_teams_urls(league)

serieA_standard <- fb_team_player_stats(team_urls= teams, stat_type= "standard")
```

**Comment by JaseZiv** [comment]
Going to mark this as closed for now.

Please raise another issue if the matter persists.
