### ISSUE TITLE
Downloading Transfer Data with tm_tem_transfers()

### ISSUE THREAD

**Issue by bogu399** [JaseZiv/worldfootballR#76]
I tried follow the example code from _https://jaseziv.github.io/worldfootballR/articles/extract-transfermarkt-data.html_ in the section of **Team Data** to download data. I changed the tournament from England to Brazil to get new data, but I have gotten this error

`[===================================>-----------------------------------------------------------------------------------------------------------]  25% Error in open.connection(x, "rb") :  schannel: next InitializeSecurityContext failed: SEC_E_MESSAGE_ALTERED (0x8009030F) - A mensagem ou assinatura fornecida para verificação foi alterada`

The code that I have used
`team_urls <- tm_league_team_urls(country_name = "Brazil", start_year = 2020)`
`bra_xfers_2020 <- tm_team_transfers(team_url = team_urls, transfer_window = "all")`

How could I solve this snippet?

**Comment by JaseZiv** [comment]
Hi,

When running the code you've provided, it runs fine for me locally. I'm using:
![image](https://user-images.githubusercontent.com/31471783/147397061-a258189f-0fc2-4007-ae5f-fe14f952ec7b.png)


What is the system info you're running? Also, can you confirm you're still having the issue as it might have just been a weird internet issue at that time?

**Comment by JaseZiv** [comment]
Going to mark this as closed for now. 

Please raise another issue if the matter persists.
