### ISSUE TITLE
Add new source

### ISSUE THREAD

**Issue by Jes-Lop** [JaseZiv/worldfootballR#89]
Would it be possible to add information from this page? [https://footystats.org/](https://footystats.org/)

It has some data that might be interesting, such as xGs for some leagues that cannot be found elsewhere.

**Comment by JaseZiv** [comment]
I think with the integration of Fotmob data (which has xG for a number of leagues), I will mark this as closed as that site doesn't appear to add any extra value to the functions currently in the package.

Feel free to re submit an issue if you have other examples from this site that would add value, or from any other site not currently in the library.

Thanks
