### ISSUE TITLE
Error: object 'read_html' is not exported by 'namespace:rvest'

### ISSUE THREAD

**Issue by rvelezDraftea** [JaseZiv/worldfootballR#99]
Installing the package, it throws an error that rvest doesn't have read_html. Maybe is from package xml2?

**Comment by JaseZiv** [comment]
Interesting. Can you please provide the code and full error message that you're experiencing? Can be a screen shot if easiest. 

Might also help if you try installing `rvest` and `xml2` separately, then trying to install `worldfootballR`.

Let me know how you go.

**Comment by tonyelhabr** [comment]
I'm guessing you have a version of `rvest` less than 1.0.0. `read_html` is originally from `xml2`, but it's re-exported from `rvest` in versions >=1.0.0.

**Comment by rvelezDraftea** [comment]
It worksssssssssss!!! Wuwuwuwu

**Comment by rvelezDraftea** [comment]
One last doubt,

Fotmob functions are only available in the repo, right? If I download from CRAN, they dont come

**Comment by rvelezDraftea** [comment]
Hello! On last doubt:

When you fetch data from fotmob from the players, in the stats column that has a data frame inside, why are more than 1 row per user?
For example, in your’s Salah example in the articles, it show 6 rows for the stats for one game. Which one is the “good” one? The first? The last?

Thanks!
Román AVJ

**Comment by tonyelhabr** [comment]
this was a bug noted in #98 . #100 fixes the issue. there should just be 1 row per player

**Comment by JaseZiv** [comment]
This has been resolved in `v0.4.10.4000`
